# NAME: FARHANKHAN PATHAN
# ROLL no.: 61
# Class: CSAI_D-3

1.Perform the following operations using Python on suitable data sets:

Read data from different formats (like csv, xls)
Find Shape of Data
Find Missing Values
Find data type of each column
Finding out Zero's
Indexing and selecting data, sort data,
Describe attributes of data, checking data types of each column,
counting unique values of data, format of each column, converting variable data type (e.g. from long to short, vice versa)

# IMPORTING DEPENDENCIES

In [ ]:
import pandas as pd;
import numpy as np;

## VIEWING DATA

Reading from a csv file:

In [ ]:
df_csv = pd.read_csv("output.csv");

print(df_csv)

                     date         price  bedrooms  bathrooms  sqft_living  \
0     2014-05-02 00:00:00  3.130000e+05       3.0       1.50         1340
1     2014-05-02 00:00:00  2.384000e+06       5.0       2.50         3650
2     2014-05-02 00:00:00  3.420000e+05       3.0       2.00         1930
3     2014-05-02 00:00:00  4.200000e+05       3.0       2.25         2000
4     2014-05-02 00:00:00  5.500000e+05       4.0       2.50         1940
...                   ...           ...       ...        ...          ...
4595  2014-07-09 00:00:00  3.081667e+05       3.0       1.75         1510
4596  2014-07-09 00:00:00  5.343333e+05       3.0       2.50         1460
4597  2014-07-09 00:00:00  4.169042e+05       3.0       2.50         3010
4598  2014-07-10 00:00:00  2.034000e+05       4.0       2.00         2090
4599  2014-07-10 00:00:00  2.206000e+05       3.0       2.50         1490

      sqft_lot  floors  waterfront  view  condition  sqft_above  \
0         7912     1.5           0     0          3        1340
1         9050     2.0           0     4          5        3370
2        11947     1.0           0     0          4        1930
3         8030     1.0           0     0          4        1000
4        10500     1.0           0     0          4        1140
...        ...     ...         ...   ...        ...         ...
4595      6360     1.0           0     0          4        1510
4596      7573     2.0           0     0          3        1460
4597      7014     2.0           0     0          3        3010
4598      6630     1.0           0     0          3        1070
4599      8102     2.0           0     0          4        1490

      sqft_basement  yr_built  yr_renovated                    street  \
0                 0      1955          2005      18810 Densmore Ave N
1               280      1921             0           709 W Blaine St
2                 0      1966             0  26206-26214 143rd Ave SE
3              1000      1963             0           857 170th Pl NE
4               800      1976          1992         9105 170th Ave NE
...             ...       ...           ...                       ...
4595              0      1954          1979            501 N 143rd St
4596              0      1983          2009          14855 SE 10th Pl
4597              0      2009             0          759 Ilwaco Pl NE
4598           1020      1974             0         5148 S Creston St
4599              0      1990             0         18717 SE 258th St

           city  statezip country
0     Shoreline  WA 98133     USA
1       Seattle  WA 98119     USA
2          Kent  WA 98042     USA
3      Bellevue  WA 98008     USA
4       Redmond  WA 98052     USA
...         ...       ...     ...
4595    Seattle  WA 98133     USA
4596   Bellevue  WA 98007     USA
4597     Renton  WA 98059     USA
4598    Seattle  WA 98178     USA
4599  Covington  WA 98042     USA

[4600 rows x 18 columns]

Reading from a excel file:

In [ ]:
df_xls = pd.read_excel("fwc22_qatar.xlsx");

print(df_xls)

   GROUP_NAME  TEAM_RANK_WITHIN_GROUP TEAM_NAME_ABBR      TEAM_NAME  GP  W  D  \
0     Group A                       1            NED    Netherlands   3  2  1
1     Group A                       2            SEN        Senegal   3  2  0
2     Group A                       3            ECU        Ecuador   3  1  1
3     Group A                       4            QAT          Qatar   3  0  0
4     Group B                       1            ENG        England   3  2  1
5     Group B                       2            USA  United States   3  1  2
6     Group B                       3            IRN           Iran   3  1  0
7     Group B                       4            WAL          Wales   3  0  1
8     Group C                       1            ARG      Argentina   3  2  0
9     Group C                       2            POL         Poland   3  1  1
10    Group C                       3            MEX         Mexico   3  1  1
11    Group C                       4            KSA   Saudi Arabia   3  1  0
12    Group D                       1            FRA         France   3  2  0
13    Group D                       2            AUS      Australia   3  2  0
14    Group D                       3            TUN        Tunisia   3  1  1
15    Group D                       4            DEN        Denmark   3  0  1
16    Group E                       1            JPN          Japan   3  2  0
17    Group E                       2            ESP          Spain   3  1  1
18    Group E                       3            GER        Germany   3  1  1
19    Group E                       4            CRC     Costa Rica   3  1  0
20    Group F                       1            MAR        Morocco   3  2  1
21    Group F                       2            CRO        Croatia   3  1  2
22    Group F                       3            BEL        Belgium   3  1  1
23    Group F                       4            CAN         Canada   3  0  0
24    Group G                       1            BRA         Brazil   3  2  0
25    Group G                       2            SUI    Switzerland   3  2  0
26    Group G                       3            CMR       Cameroon   3  1  1
27    Group G                       4            SRB         Serbia   3  0  1
28    Group H                       1            POR       Portugal   3  2  0
29    Group H                       2            KOR    South Korea   3  1  1
30    Group H                       3            URU        Uruguay   3  1  1
31    Group H                       4            GHA          Ghana   3  1  0

    L  GS  GC  GD  Pts
0   0   5   1   4    7
1   1   5   4   1    6
2   1   4   3   1    4
3   3   1   7  -6    0
4   0   9   2   7    7
5   0   2   1   1    5
6   2   4   7  -3    3
7   2   1   6  -5    1
8   1   5   2   3    6
9   1   2   2   0    4
10  1   2   3  -1    4
11  2   3   5  -2    3
12  1   6   3   3    6
13  1   3   4  -1    6
14  1   1   1   0    4
15  2   1   3  -2    1
16  1   4   3   1    6
17  1   9   3   6    4
18  1   6   5   1    4
19  2   3  11  -8    3
20  0   4   1   3    7
21  0   4   1   3    5
22  1   1   2  -1    4
23  3   2   7  -5    0
24  1   3   1   2    6
25  1   4   3   1    6
26  1   4   4   0    4
27  2   5   8  -3    1
28  1   6   4   2    6
29  1   4   4   0    4
30  1   2   2   0    4
31  2   5   7  -2    3

Reading from a json file:

In [ ]:
df_json = pd.read_json("fifa22.json");

print(df_json)

                                             GROUP_A  \
0  {'RANK_1': {'TEAM': {'TEAM_NAME_ABBR': 'NED', ...
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN
5                                                NaN
6                                                NaN
7                                                NaN

                                             GROUP_B  \
0                                                NaN
1  {'RANK_1': {'TEAM': {'TEAM_NAME_ABBR': 'ENG', ...
2                                                NaN
3                                                NaN
4                                                NaN
5                                                NaN
6                                                NaN
7                                                NaN

                                             GROUP_C  \
0                                                NaN
1                                                NaN
2  {'RANK_1': {'TEAM': {'TEAM_NAME_ABBR': 'ARG', ...
3                                                NaN
4                                                NaN
5                                                NaN
6                                                NaN
7                                                NaN

                                             GROUP_D  \
0                                                NaN
1                                                NaN
2                                                NaN
3  {'RANK_1': {'TEAM': {'TEAM_NAME_ABBR': 'FRA', ...
4                                                NaN
5                                                NaN
6                                                NaN
7                                                NaN

                                             GROUP_E  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4  {'RANK_1': {'TEAM': {'TEAM_NAME_ABBR': 'JPN', ...
5                                                NaN
6                                                NaN
7                                                NaN

                                             GROUP_F  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN
5  {'RANK_1': {'TEAM': {'TEAM_NAME_ABBR': 'MAR', ...
6                                                NaN
7                                                NaN

                                             GROUP_G  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN
5                                                NaN
6  {'RANK_1': {'TEAM': {'TEAM_NAME_ABBR': 'BRA', ...
7                                                NaN

                                             GROUP_H
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN
5                                                NaN
6                                                NaN
7  {'RANK_1': {'TEAM': {'TEAM_NAME_ABBR': 'POR', ...

# Creating a DataFrame

In [ ]:
import pandas as pd

data = {
    "Brand": ["Samsung","Apple","Xiaomi","Oppo","Vivo","Realme","OnePlus","Nokia","Motorola","Pixel","Huawei"],
    "Model": [
        "S24 Ultra","iPhone 16 Pro","Xiaomi 14","Find X7"," X100 Pro","GT 6","OnePlus 12","Nokia X30","Edge 40","Pixel 8 Pro","Mate 50 pro"
    ],
    "Price": [20000,70000,15000,18000,17000,14000,35000,16000,19000,60000,20000],
    "Rating": ["NaN",4.8,"NaN",4.2,4.1,"NaN",4.6,3.9,"NaN",4.7,4.1]
}

df = pd.DataFrame(data)
df

       Brand          Model  Price Rating
0    Samsung      S24 Ultra  20000    NaN
1      Apple  iPhone 16 Pro  70000    4.8
2     Xiaomi      Xiaomi 14  15000    NaN
3       Oppo        Find X7  18000    4.2
4       Vivo       X100 Pro  17000    4.1
5     Realme           GT 6  14000    NaN
6    OnePlus     OnePlus 12  35000    4.6
7      Nokia      Nokia X30  16000    3.9
8   Motorola        Edge 40  19000    NaN
9      Pixel    Pixel 8 Pro  60000    4.7
10    Huawei    Mate 50 pro  20000    4.1

**REPLACING THE "NaN"** WITH THE AVG VALUE FOR RATING

In [ ]:
c = avg =0;
for element in df["Rating"]:
    if element != "NaN":
        c += 1;
        avg += element;
avg = avg/c;

df = df.replace(to_replace="NaN", value= avg);

df

/tmp/ipython-input-200351380.py:8: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace(to_replace="NaN", value= avg);

       Brand          Model  Price    Rating
0    Samsung      S24 Ultra  20000  4.342857
1      Apple  iPhone 16 Pro  70000  4.800000
2     Xiaomi      Xiaomi 14  15000  4.342857
3       Oppo        Find X7  18000  4.200000
4       Vivo       X100 Pro  17000  4.100000
5     Realme           GT 6  14000  4.342857
6    OnePlus     OnePlus 12  35000  4.600000
7      Nokia      Nokia X30  16000  3.900000
8   Motorola        Edge 40  19000  4.342857
9      Pixel    Pixel 8 Pro  60000  4.700000
10    Huawei    Mate 50 pro  20000  4.100000

**DATA TYPE** FOR EACH COLUMN IN DATA FRAME

In [ ]:
df_cols = df.dtypes;
df_cols

Brand      object
Model      object
Price       int64
Rating    float64
dtype: object

**SHAPE** OF THE DATA FRAME

In [ ]:
df.shape

(11, 4)

**CHECKING ZERO ROWS** IN THE DATA FRAME

In [ ]:
df[df['Price'] == 0]

Empty DataFrame
Columns: [Brand, Model, Price, Rating]
Index: []

# FORMAT OF DATA

FORMAT OF EACH COLUMN:

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Brand   11 non-null     object
 1   Model   11 non-null     object
 2   Price   11 non-null     int64
 3   Rating  11 non-null     float64
dtypes: float64(1), int64(1), object(2)
memory usage: 484.0+ bytes

**DESCRIBE ATTRIBUTES** OF DATA

In [ ]:
df.describe()

              Price     Rating
count     11.000000  11.000000
mean   27636.363636   4.342857
std    19428.189454   0.271504
min    14000.000000   3.900000
25%    16500.000000   4.150000
50%    19000.000000   4.342857
75%    27500.000000   4.471429
max    70000.000000   4.800000

INCLUDING OBJECT

In [ ]:
df.describe(include="object")

          Brand      Model
count        11         11
unique       11         11
top     Samsung  S24 Ultra
freq          1          1

# **Selection**

SELECTING SPECIFIC ROWS

In [ ]:
print(df.loc[0]);

Brand       Samsung
Model     S24 Ultra
Price         20000
Rating     4.342857
Name: 0, dtype: object

SLICING BASED ON MULTIPLE ROWS

In [ ]:
df.loc[0:5]

     Brand          Model  Price    Rating
0  Samsung      S24 Ultra  20000  4.342857
1    Apple  iPhone 16 Pro  70000  4.800000
2   Xiaomi      Xiaomi 14  15000  4.342857
3     Oppo        Find X7  18000  4.200000
4     Vivo       X100 Pro  17000  4.100000
5   Realme           GT 6  14000  4.342857

SLICING BASED ON ROWS & COLS USING iloc()

In [ ]:
df.iloc[2:4,0:3]

    Brand      Model  Price
2  Xiaomi  Xiaomi 14  15000
3    Oppo    Find X7  18000

SELECTING SPECIFIC COLUMNS

In [ ]:
df.loc[:,["Brand","Price"]]

       Brand  Price
0    Samsung  20000
1      Apple  70000
2     Xiaomi  15000
3       Oppo  18000
4       Vivo  17000
5     Realme  14000
6    OnePlus  35000
7      Nokia  16000
8   Motorola  19000
9      Pixel  60000
10    Huawei  20000

SELECTION USING CONDITION : DISPLAYING MOBILES WITH PRICE > 10000

In [ ]:
df[df['Price']>10000]

       Brand          Model  Price    Rating
0    Samsung      S24 Ultra  20000  4.342857
1      Apple  iPhone 16 Pro  70000  4.800000
2     Xiaomi      Xiaomi 14  15000  4.342857
3       Oppo        Find X7  18000  4.200000
4       Vivo       X100 Pro  17000  4.100000
5     Realme           GT 6  14000  4.342857
6    OnePlus     OnePlus 12  35000  4.600000
7      Nokia      Nokia X30  16000  3.900000
8   Motorola        Edge 40  19000  4.342857
9      Pixel    Pixel 8 Pro  60000  4.700000
10    Huawei    Mate 50 pro  20000  4.100000

# SORTING

**SORT BY COLUMN** :SORT MOBILES BY PRICE

In [ ]:
df.sort_values(by='Price')

       Brand          Model  Price    Rating
5     Realme           GT 6  14000  4.342857
2     Xiaomi      Xiaomi 14  15000  4.342857
7      Nokia      Nokia X30  16000  3.900000
4       Vivo       X100 Pro  17000  4.100000
3       Oppo        Find X7  18000  4.200000
8   Motorola        Edge 40  19000  4.342857
10    Huawei    Mate 50 pro  20000  4.100000
0    Samsung      S24 Ultra  20000  4.342857
6    OnePlus     OnePlus 12  35000  4.600000
9      Pixel    Pixel 8 Pro  60000  4.700000
1      Apple  iPhone 16 Pro  70000  4.800000

**SORT BY COLUMN** :SORT MOBILES BY RATINGS (DEC)

In [ ]:
df.sort_values(by='Rating', ascending=False)

       Brand          Model  Price    Rating
1      Apple  iPhone 16 Pro  70000  4.800000
9      Pixel    Pixel 8 Pro  60000  4.700000
6    OnePlus     OnePlus 12  35000  4.600000
2     Xiaomi      Xiaomi 14  15000  4.342857
0    Samsung      S24 Ultra  20000  4.342857
8   Motorola        Edge 40  19000  4.342857
5     Realme           GT 6  14000  4.342857
3       Oppo        Find X7  18000  4.200000
4       Vivo       X100 Pro  17000  4.100000
10    Huawei    Mate 50 pro  20000  4.100000
7      Nokia      Nokia X30  16000  3.900000

**SORT BY MULTIPLE COLUMNS** : BY RATINGS (DEC) & PRICE (ASC)

In [ ]:
df.sort_values(
    by=['Rating', 'Price'],
    ascending=[False, True]
)

       Brand          Model  Price    Rating
1      Apple  iPhone 16 Pro  70000  4.800000
9      Pixel    Pixel 8 Pro  60000  4.700000
6    OnePlus     OnePlus 12  35000  4.600000
5     Realme           GT 6  14000  4.342857
2     Xiaomi      Xiaomi 14  15000  4.342857
8   Motorola        Edge 40  19000  4.342857
0    Samsung      S24 Ultra  20000  4.342857
3       Oppo        Find X7  18000  4.200000
4       Vivo       X100 Pro  17000  4.100000
10    Huawei    Mate 50 pro  20000  4.100000
7      Nokia      Nokia X30  16000  3.900000

# DATATYPE CONVERSION

In [ ]:
df['Rating'] = df['Rating'].replace("NaN", np.nan)

CHECKING DATA BEFORE CONVERSION

In [ ]:
df.dtypes

Brand      object
Model      object
Price       int64
Rating    float64
dtype: object

CONVERT PRICE FROM int64 TO float64

In [ ]:
df['Price'] = df['Price'].astype(float)
df.dtypes

Brand      object
Model      object
Price     float64
Rating    float64
dtype: object

CONVERTING BRAND object TO string

In [ ]:
df['Brand'] = df['Brand'].astype('string')
df.dtypes

Brand     string[python]
Model             object
Price            float64
Rating           float64
dtype: object

CHECKING DATA AFTER CONVERSION

In [ ]:
df.dtypes

Brand     string[python]
Model             object
Price            float64
Rating           float64
dtype: object

# UNIQUE VALUES

COUNT UNIQUE VALUES IN EACH COLUMN

In [ ]:
df.nunique()

Brand     11
Model     11
Price     10
Rating     7
dtype: int64

COUNT UNIQUE VALUES IN SPECIFIC COLUMN : BRAND COL

In [ ]:
df['Brand'].nunique()

11

COUNT FREQUENCY OF EACH VALUE

In [ ]:
df['Rating'].value_counts()

Rating
4.342857    4
4.100000    2
4.800000    1
4.200000    1
4.600000    1
3.900000    1
4.700000    1
Name: count, dtype: int64

# MERGE

CREATE A NEW DATAFRAME TO JOIN

In [ ]:
brand_country = pd.DataFrame({
    "Brand": ["Samsung", "Apple", "Xiaomi", "Oppo", "Vivo", "Realme", "OnePlus", "Nokia", "Motorola", "Pixel"],
    "Country": ["South Korea", "USA", "China", "China", "China", "China", "China", "Finland", "USA", "USA"]
})

brand_country

      Brand      Country
0   Samsung  South Korea
1     Apple          USA
2    Xiaomi        China
3      Oppo        China
4      Vivo        China
5    Realme        China
6   OnePlus        China
7     Nokia      Finland
8  Motorola          USA
9     Pixel          USA

MERGE TWO FRAMES ON A COMMON COLUMN

In [ ]:
pd.merge(df, brand_country, on="Brand")

      Brand          Model    Price    Rating      Country
0   Samsung      S24 Ultra  20000.0  4.342857  South Korea
1     Apple  iPhone 16 Pro  70000.0  4.800000          USA
2    Xiaomi      Xiaomi 14  15000.0  4.342857        China
3      Oppo        Find X7  18000.0  4.200000        China
4      Vivo       X100 Pro  17000.0  4.100000        China
5    Realme           GT 6  14000.0  4.342857        China
6   OnePlus     OnePlus 12  35000.0  4.600000        China
7     Nokia      Nokia X30  16000.0  3.900000      Finland
8  Motorola        Edge 40  19000.0  4.342857          USA
9     Pixel    Pixel 8 Pro  60000.0  4.700000          USA

# GROUPING

GROUP BY BRAND & CALC MEAN

In [ ]:
df.groupby("Brand")["Price"].mean()

Brand
Apple       70000.0
Huawei      20000.0
Motorola    19000.0
Nokia       16000.0
OnePlus     35000.0
Oppo        18000.0
Pixel       60000.0
Realme      14000.0
Samsung     20000.0
Vivo        17000.0
Xiaomi      15000.0
Name: Price, dtype: float64

GROUP BY BRAND & CALC PRICE AND RATING MEAN

In [ ]:
df.groupby("Brand")[["Price", "Rating"]].mean()

            Price    Rating
Brand
Apple     70000.0  4.800000
Huawei    20000.0  4.100000
Motorola  19000.0  4.342857
Nokia     16000.0  3.900000
OnePlus   35000.0  4.600000
Oppo      18000.0  4.200000
Pixel     60000.0  4.700000
Realme    14000.0  4.342857
Samsung   20000.0  4.342857
Vivo      17000.0  4.100000
Xiaomi    15000.0  4.342857