# NAME:FARHANKHAN PATHAN
# ROLL NO.: 61
# CLASS: CSAID-D-3

# ASSIGNMENT 2

2. Perform the following operations using  Python on the data sets:

Compute and display summary statistics for each feature available in the dataset. (e.g. minimum value, maximum value, mean, range, standard deviation, variance and percentiles
Illustrate the feature distributions using histogram.
Data cleaning, Data integration, Data transformation, Data model building (e.g. Classification)

# CHECKPOINT 1 :  DISPLAY SUMMARY STATISTICS

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('assign_2.csv')

/tmp/ipython-input-4291209508.py:1: DtypeWarning: Columns (24) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('assign_2.csv')

In [ ]:
df.head()

,track_id,track_name,track_artist,track_popularity,track_album_id,track_album_name,track_album_release_date,playlist_name,playlist_id,playlist_genre,...,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,Mental_Health_Label,raga_name,raga_label,instrument
0,697MjF1454XKvZmTuqkWmD,I Miss You,Jeriqo,45,2vJ6FDg6ZMS56U8Wbiw2Oz,I Miss You,05-02-2019,Pop Hits 2000-2019,6mtYuOxzl58vSGnEDtZ9uB,edm,...,0.004910,0.000013,0.0816,0.415,174.026,216347,Normal/Unclassified,NaN,Bageshree,Unknown
1,3x2bXiU0o4WbsPkawXlfDA,Who Are You,The Who,17,6LRJF97hgXHj8uMLHyCDbh,Who Are You (Remastered),18-08-1978,House Of The Rising Sun,1bMYfBHYBCRHY5LGkjlpSy,rock,...,0.265000,0.003130,0.1060,0.489,156.371,378707,Normal/Unclassified,NaN,Yaman,Guitar/Drums
2,0jEaPBjFAWjQTMVouRwaHi,Happy,The Beef Seeds,30,4IQn9XpweytNX2cUe2NBUH,Keepin' it Beefy,19-01-2015,Bluegrass Covers,37i9dQZF1DX56crgoe4TG3,r&b,...,0.665000,0.000000,0.1270,0.932,86.529,218044,Bipolar (Mania),NaN,Kafi,Unknown
3,5EKUb1FKsyYVaSXb41YBIj,ONE,Rev Theory,35,0gGic19XvEiHKKWBV7M4YM,ONE,15-01-2020,Rock Hard,37i9dQZF1DWWJOmJ7nRx0C,rock,...,0.000006,0.000000,0.3030,0.520,90.016,208196,Normal/Unclassified,NaN,Bageshree,Guitar/Drums
4,300DUx4tdtCdGEUXR032jA,Palace/Curse,The Internet,62,69g3CtOVg98TPOwqmI2K7Q,Ego Death,26-06-2015,NEO-soul,3q3M4VCymcMoxJ3Tl7mRqN,r&b,...,0.035100,0.000727,0.2430,0.261,67.104,440013,Normal/Unclassified,NaN,Kafi,Unknown

In [ ]:
df.describe()

,track_popularity,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms
count,32833.000000,32833.000000,32833.000000,32833.000000,32833.000000,32833.000000,32833.000000,32833.000000,32833.000000,32833.000000,32833.000000,32833.000000,32833.000000
mean,42.477081,0.654850,0.698619,5.374471,-6.719499,0.565711,0.107068,0.175334,0.084747,0.190176,0.510561,120.881132,225799.811622
std,24.984074,0.145085,0.180910,3.611657,2.988436,0.495671,0.101314,0.219633,0.224230,0.154317,0.233146,26.903624,59834.006182
min,0.000000,0.000000,0.000175,0.000000,-46.448000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4000.000000
25%,24.000000,0.563000,0.581000,2.000000,-8.171000,0.000000,0.041000,0.015100,0.000000,0.092700,0.331000,99.960000,187819.000000
50%,45.000000,0.672000,0.721000,6.000000,-6.166000,1.000000,0.062500,0.080400,0.000016,0.127000,0.512000,121.984000,216000.000000
75%,62.000000,0.761000,0.840000,9.000000,-4.645000,1.000000,0.132000,0.255000,0.004830,0.248000,0.693000,133.918000,253585.000000
max,100.000000,0.983000,1.000000,11.000000,1.275000,1.000000,0.918000,0.994000,0.994000,0.996000,0.991000,239.440000,517810.000000

In [ ]:
numeric_df = df.select_dtypes(include=[np.number])

Using Built-in Functions

In [ ]:
summary = pd.DataFrame({
    'Minimum': numeric_df.min(),
    'Maximum': numeric_df.max(),
    'Mean': numeric_df.mean(),
    'Range': numeric_df.max() - numeric_df.min(),
    'Standard Deviation': numeric_df.std(),
    'Variance': numeric_df.var(),
    '25th Percentile': numeric_df.quantile(0.25),
    '50th Percentile (Median)': numeric_df.quantile(0.50),
    '75th Percentile': numeric_df.quantile(0.75)
})

summary

,Minimum,Maximum,Mean,Range,Standard Deviation,Variance,25th Percentile,50th Percentile (Median),75th Percentile
track_popularity,0.000000,100.000,42.477081,100.000000,24.984074,6.242040e+02,24.0000,45.000000,62.00000
danceability,0.000000,0.983,0.654850,0.983000,0.145085,2.104975e-02,0.5630,0.672000,0.76100
energy,0.000175,1.000,0.698619,0.999825,0.180910,3.272844e-02,0.5810,0.721000,0.84000
key,0.000000,11.000,5.374471,11.000000,3.611657,1.304407e+01,2.0000,6.000000,9.00000
loudness,-46.448000,1.275,-6.719499,47.723000,2.988436,8.930752e+00,-8.1710,-6.166000,-4.64500
mode,0.000000,1.000,0.565711,1.000000,0.495671,2.456895e-01,0.0000,1.000000,1.00000
speechiness,0.000000,0.918,0.107068,0.918000,0.101314,1.026455e-02,0.0410,0.062500,0.13200
acousticness,0.000000,0.994,0.175334,0.994000,0.219633,4.823845e-02,0.0151,0.080400,0.25500
instrumentalness,0.000000,0.994,0.084747,0.994000,0.224230,5.027915e-02,0.0000,0.000016,0.00483
liveness,0.000000,0.996,0.190176,0.996000,0.154317,2.381382e-02,0.0927,0.127000,0.24800
valence,0.000000,0.991,0.510561,0.991000,0.233146,5.435705e-02,0.3310,0.512000,0.69300
tempo,0.000000,239.440,120.881132,239.440000,26.903624,7.238050e+02,99.9600,121.984000,133.91800
duration_ms,4000.000000,517810.000,225799.811622,513810.000000,59834.006182,3.580108e+09,187819.0000,216000.000000,253585.00000

Creating User Define Functions for the Built-in functions

In [ ]:
import pandas as pd

numbers = [12, 15, 12, 18, 20, 15, 25]

def mean(numbers):
    return sum(numbers) / len(numbers)

def minimum(numbers):
    return min(numbers)

def maximum(numbers):
    return max(numbers)

def median(numbers):
    sorted_nums = sorted(numbers)
    n = len(sorted_nums)
    if n % 2 == 0:
        return (sorted_nums[n//2 - 1] + sorted_nums[n//2]) / 2
    else:
        return sorted_nums[n//2]

def mode(numbers):
    freq = {}
    for num in numbers:
        freq[num] = freq.get(num, 0) + 1
    max_freq = max(freq.values())
    return [k for k, v in freq.items() if v == max_freq]

def variance(numbers):
    m = mean(numbers)
    return sum((x - m) ** 2 for x in numbers) / (len(numbers) - 1)

def std(numbers):
    return variance(numbers) ** 0.5

def range(numbers):
    return maximum(numbers) - minimum(numbers)

results = {
    "Mean": mean(numbers),
    "Minimum": minimum(numbers),
    "Maximum": maximum(numbers),
    "Median": median(numbers),
    "Mode": mode(numbers),
    "Variance": variance(numbers),
    "Standard Deviation": std(numbers),
    "Range": range(numbers)
}

df = pd.DataFrame(list(results.items()), columns=["Statistic", "Value"])
df

            Statistic      Value
0                Mean  16.714286
1             Minimum         12
2             Maximum         25
3              Median         15
4                Mode   [12, 15]
5            Variance  21.904762
6  Standard Deviation   4.680252
7               Range         13

# CHECKPOINT 2: DATA CLEANING

In [ ]:
data = {
    "Emp_ID": [201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220],
    "Name": ["Ankit","Pooja","Ravi","Sonal","Manish","Manish","Kiran","Neha","Aarav","Riya",
             "Vikas","Simran","Sameer","Divya",None,"Ajay","Tina","Kabir","Rohit","Nisha"],
    "Department": ["IT","HR","Finance","IT","Sales","Sales","sales","HR","Finance","IT",
                   "Marketing","HR","Finance","IT","Sales","Marketing","HR","Finance","Sales","IT"],
    "Age": [25,28,None,27,35,35,29,26,40,23,30,None,38,24,31,29,27,45,33,26],
    "Salary": [55000,48000,60000,None,72000,72000,50000,45000,95000,None,
               58000,52000,-8000,51000,61000,56000,47000,105000,65000,49000],
    "Experience": [None,4,3,5,10,10,4,2,15,1,6,5,12,None,7,5,3,20,8,3],
    "Rating": [4.2,3.8,4.0,None,4.9,4.9,3.2,2.8,5.5,5.5,
               None,4.0,4.7,3.9,4.0,3.6,2.1,4.8,3.0,4.3],
    "Bonus": [5000,3000,None,7000,12000,12000,-2000,2500,50000,1000,
              None,4000,8000,None,6000,4500,2000,15000,None,3800]
}

df = pd.DataFrame(data)
df

    Emp_ID    Name Department   Age    Salary  Experience  Rating    Bonus
0      201   Ankit         IT  25.0   55000.0         NaN     4.2   5000.0
1      202   Pooja         HR  28.0   48000.0         4.0     3.8   3000.0
2      203    Ravi    Finance   NaN   60000.0         3.0     4.0      NaN
3      204   Sonal         IT  27.0       NaN         5.0     NaN   7000.0
4      205  Manish      Sales  35.0   72000.0        10.0     4.9  12000.0
5      206  Manish      Sales  35.0   72000.0        10.0     4.9  12000.0
6      207   Kiran      sales  29.0   50000.0         4.0     3.2  -2000.0
7      208    Neha         HR  26.0   45000.0         2.0     2.8   2500.0
8      209   Aarav    Finance  40.0   95000.0        15.0     5.5  50000.0
9      210    Riya         IT  23.0       NaN         1.0     5.5   1000.0
10     211   Vikas  Marketing  30.0   58000.0         6.0     NaN      NaN
11     212  Simran         HR   NaN   52000.0         5.0     4.0   4000.0
12     213  Sameer    Finance  38.0   -8000.0        12.0     4.7   8000.0
13     214   Divya         IT  24.0   51000.0         NaN     3.9      NaN
14     215    None      Sales  31.0   61000.0         7.0     4.0   6000.0
15     216    Ajay  Marketing  29.0   56000.0         5.0     3.6   4500.0
16     217    Tina         HR  27.0   47000.0         3.0     2.1   2000.0
17     218   Kabir    Finance  45.0  105000.0        20.0     4.8  15000.0
18     219   Rohit      Sales  33.0   65000.0         8.0     3.0      NaN
19     220   Nisha         IT  26.0   49000.0         3.0     4.3   3800.0

1. HANDLING MISSING VALUES

In [ ]:
df.isnull()

    Emp_ID   Name  Department    Age  Salary  Experience  Rating  Bonus
0    False  False       False  False   False        True   False  False
1    False  False       False  False   False       False   False  False
2    False  False       False   True   False       False   False   True
3    False  False       False  False    True       False    True  False
4    False  False       False  False   False       False   False  False
5    False  False       False  False   False       False   False  False
6    False  False       False  False   False       False   False  False
7    False  False       False  False   False       False   False  False
8    False  False       False  False   False       False   False  False
9    False  False       False  False    True       False   False  False
10   False  False       False  False   False       False    True   True
11   False  False       False   True   False       False   False  False
12   False  False       False  False   False       False   False  False
13   False  False       False  False   False        True   False   True
14   False   True       False  False   False       False   False  False
15   False  False       False  False   False       False   False  False
16   False  False       False  False   False       False   False  False
17   False  False       False  False   False       False   False  False
18   False  False       False  False   False       False   False   True
19   False  False       False  False   False       False   False  False

In [ ]:
df.isna().sum()

Emp_ID        0
Name          1
Department    0
Age           2
Salary        2
Experience    2
Rating        2
Bonus         4
dtype: int64

In [ ]:
df.notnull()

    Emp_ID   Name  Department    Age  Salary  Experience  Rating  Bonus
0     True   True        True   True    True        True    True   True
1     True   True        True   True    True        True    True   True
2     True   True        True  False    True        True    True  False
3     True   True        True   True   False        True    True   True
4     True   True        True   True    True        True    True   True
5     True   True        True   True    True        True    True   True
6     True   True        True   True    True        True    True   True
7     True   True        True   True    True        True    True   True
8     True   True        True   True    True        True    True   True
9     True   True        True   True    True        True    True   True
10    True   True        True   True    True        True   False  False
11    True   True        True   True    True        True    True   True
12    True   True        True   True    True        True    True   True
13    True   True        True   True    True       False    True   True
14    True  False        True   True    True        True    True   True
15    True   True        True   True    True        True    True   True
16    True   True        True   True    True        True    True   True
17    True   True        True   True    True        True    True   True
18    True   True        True   True    True        True    True   True
19    True   True        True   True    True        True    True   True

In [ ]:
df_drop_rows = df.dropna()
df_drop_rows

,Emp_ID,Name,Department,Age,Salary,Experience,Rating,Bonus
0,201,Ankit,IT,25,55000.0,2.0,4.2,5000.0
1,202,Pooja,HR,28,48000.0,4.0,3.8,3000.0
4,205,Manish,Sales,35,72000.0,10.0,4.9,12000.0
5,206,Manish,Sales,35,72000.0,10.0,4.9,12000.0
6,207,Kiran,sales,29,50000.0,4.0,3.2,-2000.0
7,208,Neha,HR,26,45000.0,2.0,2.8,2500.0
8,209,Aarav,Finance,40,95000.0,15.0,5.5,50000.0
9,210,Riya,IT,23,30000.0,1.0,3.5,1000.0
11,212,Simran,HR,twenty-nine,52000.0,5.0,4.1,4000.0
12,213,Sameer,Finance,38,-8000.0,12.0,4.7,8000.0
15,216,Ajay,Marketing,29,56000.0,5.0,3.6,4500.0
16,217,Tina,HR,27,47000.0,3.0,2.1,2000.0
17,218,Kabir,Finance,45,105000.0,20.0,4.8,15000.0
18,219,Rohit,Sales,33,65000.0,8.0,3.0,3000.0
19,220,Nisha,IT,26,49000.0,3.0,4.3,3800.0

In [ ]:
df["Age"] = df["Age"].fillna(df["Age"].median())
df["Salary"] = df["Salary"].fillna(df["Salary"].mean())
df["Experience"] = df["Experience"].fillna(df["Experience"].median())
df["Rating"] = df["Rating"].fillna(df["Rating"].mean())
df["Bonus"] = df["Bonus"].fillna(df["Bonus"].mean())
df

,Emp_ID,Name,Department,Age,Salary,Experience,Rating,Bonus
0,201,Ankit,IT,25.0,55000.000000,5.0,4.200000,5000.0
1,202,Pooja,HR,28.0,48000.000000,4.0,3.800000,3000.0
2,203,Ravi,Finance,29.0,60000.000000,3.0,4.000000,8362.5
3,204,Sonal,IT,27.0,57388.888889,5.0,4.066667,7000.0
4,205,Manish,Sales,35.0,72000.000000,10.0,4.900000,12000.0
5,206,Manish,Sales,35.0,72000.000000,10.0,4.900000,12000.0
6,207,Kiran,sales,29.0,50000.000000,4.0,3.200000,-2000.0
7,208,Neha,HR,26.0,45000.000000,2.0,2.800000,2500.0
8,209,Aarav,Finance,40.0,95000.000000,15.0,5.500000,50000.0
9,210,Riya,IT,23.0,57388.888889,1.0,5.500000,1000.0
10,211,Vikas,Marketing,30.0,58000.000000,6.0,4.066667,8362.5
11,212,Simran,HR,29.0,52000.000000,5.0,4.000000,4000.0
12,213,Sameer,Finance,38.0,-8000.000000,12.0,4.700000,8000.0
13,214,Divya,IT,24.0,51000.000000,5.0,3.900000,8362.5
14,215,None,Sales,31.0,61000.000000,7.0,4.000000,6000.0
15,216,Ajay,Marketing,29.0,56000.000000,5.0,3.600000,4500.0
16,217,Tina,HR,27.0,47000.000000,3.0,2.100000,2000.0
17,218,Kabir,Finance,45.0,105000.000000,20.0,4.800000,15000.0
18,219,Rohit,Sales,33.0,65000.000000,8.0,3.000000,8362.5
19,220,Nisha,IT,26.0,49000.000000,3.0,4.300000,3800.0

In [ ]:
df["Salary"] = df["Salary"].interpolate()
df["Bonus"] = df["Bonus"].interpolate()
df

,Emp_ID,Name,Department,Age,Salary,Experience,Rating,Bonus
0,201,Ankit,IT,25.0,55000.000000,5.0,4.200000,5000.0
1,202,Pooja,HR,28.0,48000.000000,4.0,3.800000,3000.0
2,203,Ravi,Finance,29.0,60000.000000,3.0,4.000000,8362.5
3,204,Sonal,IT,27.0,57388.888889,5.0,4.066667,7000.0
4,205,Manish,Sales,35.0,72000.000000,10.0,4.900000,12000.0
5,206,Manish,Sales,35.0,72000.000000,10.0,4.900000,12000.0
6,207,Kiran,sales,29.0,50000.000000,4.0,3.200000,-2000.0
7,208,Neha,HR,26.0,45000.000000,2.0,2.800000,2500.0
8,209,Aarav,Finance,40.0,95000.000000,15.0,5.500000,50000.0
9,210,Riya,IT,23.0,57388.888889,1.0,5.500000,1000.0
10,211,Vikas,Marketing,30.0,58000.000000,6.0,4.066667,8362.5
11,212,Simran,HR,29.0,52000.000000,5.0,4.000000,4000.0
12,213,Sameer,Finance,38.0,-8000.000000,12.0,4.700000,8000.0
13,214,Divya,IT,24.0,51000.000000,5.0,3.900000,8362.5
14,215,None,Sales,31.0,61000.000000,7.0,4.000000,6000.0
15,216,Ajay,Marketing,29.0,56000.000000,5.0,3.600000,4500.0
16,217,Tina,HR,27.0,47000.000000,3.0,2.100000,2000.0
17,218,Kabir,Finance,45.0,105000.000000,20.0,4.800000,15000.0
18,219,Rohit,Sales,33.0,65000.000000,8.0,3.000000,8362.5
19,220,Nisha,IT,26.0,49000.000000,3.0,4.300000,3800.0

In [ ]:
df["Rating"] = df["Rating"].replace(np.nan, df["Rating"].mean())
df

,Emp_ID,Name,Department,Age,Salary,Experience,Rating,Bonus
0,201,Ankit,IT,25.0,55000.000000,5.0,4.200000,5000.0
1,202,Pooja,HR,28.0,48000.000000,4.0,3.800000,3000.0
2,203,Ravi,Finance,29.0,60000.000000,3.0,4.000000,8362.5
3,204,Sonal,IT,27.0,57388.888889,5.0,4.066667,7000.0
4,205,Manish,Sales,35.0,72000.000000,10.0,4.900000,12000.0
5,206,Manish,Sales,35.0,72000.000000,10.0,4.900000,12000.0
6,207,Kiran,sales,29.0,50000.000000,4.0,3.200000,-2000.0
7,208,Neha,HR,26.0,45000.000000,2.0,2.800000,2500.0
8,209,Aarav,Finance,40.0,95000.000000,15.0,5.500000,50000.0
9,210,Riya,IT,23.0,57388.888889,1.0,5.500000,1000.0
10,211,Vikas,Marketing,30.0,58000.000000,6.0,4.066667,8362.5
11,212,Simran,HR,29.0,52000.000000,5.0,4.000000,4000.0
12,213,Sameer,Finance,38.0,-8000.000000,12.0,4.700000,8000.0
13,214,Divya,IT,24.0,51000.000000,5.0,3.900000,8362.5
14,215,None,Sales,31.0,61000.000000,7.0,4.000000,6000.0
15,216,Ajay,Marketing,29.0,56000.000000,5.0,3.600000,4500.0
16,217,Tina,HR,27.0,47000.000000,3.0,2.100000,2000.0
17,218,Kabir,Finance,45.0,105000.000000,20.0,4.800000,15000.0
18,219,Rohit,Sales,33.0,65000.000000,8.0,3.000000,8362.5
19,220,Nisha,IT,26.0,49000.000000,3.0,4.300000,3800.0

2. REMOVING DUPLICATE

In [ ]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
dtype: bool

In [ ]:
df.drop_duplicates(inplace=True)
df

,Emp_ID,Name,Department,Age,Salary,Experience,Rating,Bonus
0,201,Ankit,IT,25.0,55000.000000,5.0,4.200000,5000.0
1,202,Pooja,HR,28.0,48000.000000,4.0,3.800000,3000.0
2,203,Ravi,Finance,29.0,60000.000000,3.0,4.000000,8362.5
3,204,Sonal,IT,27.0,57388.888889,5.0,4.066667,7000.0
4,205,Manish,Sales,35.0,72000.000000,10.0,4.900000,12000.0
5,206,Manish,Sales,35.0,72000.000000,10.0,4.900000,12000.0
6,207,Kiran,sales,29.0,50000.000000,4.0,3.200000,-2000.0
7,208,Neha,HR,26.0,45000.000000,2.0,2.800000,2500.0
8,209,Aarav,Finance,40.0,95000.000000,15.0,5.500000,50000.0
9,210,Riya,IT,23.0,57388.888889,1.0,5.500000,1000.0
10,211,Vikas,Marketing,30.0,58000.000000,6.0,4.066667,8362.5
11,212,Simran,HR,29.0,52000.000000,5.0,4.000000,4000.0
12,213,Sameer,Finance,38.0,-8000.000000,12.0,4.700000,8000.0
13,214,Divya,IT,24.0,51000.000000,5.0,3.900000,8362.5
14,215,None,Sales,31.0,61000.000000,7.0,4.000000,6000.0
15,216,Ajay,Marketing,29.0,56000.000000,5.0,3.600000,4500.0
16,217,Tina,HR,27.0,47000.000000,3.0,2.100000,2000.0
17,218,Kabir,Finance,45.0,105000.000000,20.0,4.800000,15000.0
18,219,Rohit,Sales,33.0,65000.000000,8.0,3.000000,8362.5
19,220,Nisha,IT,26.0,49000.000000,3.0,4.300000,3800.0

3. DATA CONVERSION

In [ ]:
df.dtypes

Emp_ID          int64
Name           object
Department     object
Age           float64
Salary        float64
Experience    float64
Rating        float64
Bonus         float64
dtype: object

In [ ]:
df["Bonus"] = df["Bonus"].astype(int)
df

,Emp_ID,Name,Department,Age,Salary,Experience,Rating,Bonus
0,201,Ankit,IT,25.0,55000.000000,5.0,4.200000,5000
1,202,Pooja,HR,28.0,48000.000000,4.0,3.800000,3000
2,203,Ravi,Finance,29.0,60000.000000,3.0,4.000000,8362
3,204,Sonal,IT,27.0,57388.888889,5.0,4.066667,7000
4,205,Manish,Sales,35.0,72000.000000,10.0,4.900000,12000
5,206,Manish,Sales,35.0,72000.000000,10.0,4.900000,12000
6,207,Kiran,sales,29.0,50000.000000,4.0,3.200000,-2000
7,208,Neha,HR,26.0,45000.000000,2.0,2.800000,2500
8,209,Aarav,Finance,40.0,95000.000000,15.0,5.500000,50000
9,210,Riya,IT,23.0,57388.888889,1.0,5.500000,1000
10,211,Vikas,Marketing,30.0,58000.000000,6.0,4.066667,8362
11,212,Simran,HR,29.0,52000.000000,5.0,4.000000,4000
12,213,Sameer,Finance,38.0,-8000.000000,12.0,4.700000,8000
13,214,Divya,IT,24.0,51000.000000,5.0,3.900000,8362
14,215,None,Sales,31.0,61000.000000,7.0,4.000000,6000
15,216,Ajay,Marketing,29.0,56000.000000,5.0,3.600000,4500
16,217,Tina,HR,27.0,47000.000000,3.0,2.100000,2000
17,218,Kabir,Finance,45.0,105000.000000,20.0,4.800000,15000
18,219,Rohit,Sales,33.0,65000.000000,8.0,3.000000,8362
19,220,Nisha,IT,26.0,49000.000000,3.0,4.300000,3800

In [ ]:
df["Age"] = pd.to_numeric(df["Age"])
df["Salary"] = pd.to_numeric(df["Salary"])
df

,Emp_ID,Name,Department,Age,Salary,Experience,Rating,Bonus
0,201,Ankit,IT,25.0,55000.000000,5.0,4.200000,5000
1,202,Pooja,HR,28.0,48000.000000,4.0,3.800000,3000
2,203,Ravi,Finance,29.0,60000.000000,3.0,4.000000,8362
3,204,Sonal,IT,27.0,57388.888889,5.0,4.066667,7000
4,205,Manish,Sales,35.0,72000.000000,10.0,4.900000,12000
5,206,Manish,Sales,35.0,72000.000000,10.0,4.900000,12000
6,207,Kiran,sales,29.0,50000.000000,4.0,3.200000,-2000
7,208,Neha,HR,26.0,45000.000000,2.0,2.800000,2500
8,209,Aarav,Finance,40.0,95000.000000,15.0,5.500000,50000
9,210,Riya,IT,23.0,57388.888889,1.0,5.500000,1000
10,211,Vikas,Marketing,30.0,58000.000000,6.0,4.066667,8362
11,212,Simran,HR,29.0,52000.000000,5.0,4.000000,4000
12,213,Sameer,Finance,38.0,-8000.000000,12.0,4.700000,8000
13,214,Divya,IT,24.0,51000.000000,5.0,3.900000,8362
14,215,None,Sales,31.0,61000.000000,7.0,4.000000,6000
15,216,Ajay,Marketing,29.0,56000.000000,5.0,3.600000,4500
16,217,Tina,HR,27.0,47000.000000,3.0,2.100000,2000
17,218,Kabir,Finance,45.0,105000.000000,20.0,4.800000,15000
18,219,Rohit,Sales,33.0,65000.000000,8.0,3.000000,8362
19,220,Nisha,IT,26.0,49000.000000,3.0,4.300000,3800

In [ ]:
df["Join_Date"] = pd.to_datetime([
    "2022-01-10","2021-05-20","2020-07-15","2021-09-01","2018-03-12",
    "2018-03-12","2020-11-25","2022-06-30","2015-08-19","2023-01-05",
    "2019-04-10","2020-02-14","2012-12-01","2022-10-10","2019-06-18",
    "2020-08-09","2021-01-20","2010-05-05","2016-07-07","2022-04-02"
])
df

,Emp_ID,Name,Department,Age,Salary,Experience,Rating,Bonus,Join_Date
0,201,Ankit,IT,25.0,55000.000000,5.0,4.200000,5000,2022-01-10
1,202,Pooja,HR,28.0,48000.000000,4.0,3.800000,3000,2021-05-20
2,203,Ravi,Finance,29.0,60000.000000,3.0,4.000000,8362,2020-07-15
3,204,Sonal,IT,27.0,57388.888889,5.0,4.066667,7000,2021-09-01
4,205,Manish,Sales,35.0,72000.000000,10.0,4.900000,12000,2018-03-12
5,206,Manish,Sales,35.0,72000.000000,10.0,4.900000,12000,2018-03-12
6,207,Kiran,sales,29.0,50000.000000,4.0,3.200000,-2000,2020-11-25
7,208,Neha,HR,26.0,45000.000000,2.0,2.800000,2500,2022-06-30
8,209,Aarav,Finance,40.0,95000.000000,15.0,5.500000,50000,2015-08-19
9,210,Riya,IT,23.0,57388.888889,1.0,5.500000,1000,2023-01-05
10,211,Vikas,Marketing,30.0,58000.000000,6.0,4.066667,8362,2019-04-10
11,212,Simran,HR,29.0,52000.000000,5.0,4.000000,4000,2020-02-14
12,213,Sameer,Finance,38.0,-8000.000000,12.0,4.700000,8000,2012-12-01
13,214,Divya,IT,24.0,51000.000000,5.0,3.900000,8362,2022-10-10
14,215,None,Sales,31.0,61000.000000,7.0,4.000000,6000,2019-06-18
15,216,Ajay,Marketing,29.0,56000.000000,5.0,3.600000,4500,2020-08-09
16,217,Tina,HR,27.0,47000.000000,3.0,2.100000,2000,2021-01-20
17,218,Kabir,Finance,45.0,105000.000000,20.0,4.800000,15000,2010-05-05
18,219,Rohit,Sales,33.0,65000.000000,8.0,3.000000,8362,2016-07-07
19,220,Nisha,IT,26.0,49000.000000,3.0,4.300000,3800,2022-04-02

In [ ]:
df = df.convert_dtypes()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Emp_ID      20 non-null     Int64
 1   Name        19 non-null     string
 2   Department  20 non-null     string
 3   Age         20 non-null     Int64
 4   Salary      20 non-null     Float64
 5   Experience  20 non-null     Int64
 6   Rating      20 non-null     Float64
 7   Bonus       20 non-null     Int64
 8   Join_Date   20 non-null     datetime64[ns]
dtypes: Float64(2), Int64(4), datetime64[ns](1), string(2)
memory usage: 1.7 KB

4. RENAMING COLUMNS

In [ ]:
df.rename(columns={"Emp_ID": "Employee_ID", "Salary": "Monthly_Salary"})

,Employee_ID,Name,Department,Age,Monthly_Salary,Experience,Rating,Bonus,Join_Date
0,201,Ankit,IT,25,55000.0,5,4.2,5000,2022-01-10
1,202,Pooja,HR,28,48000.0,4,3.8,3000,2021-05-20
2,203,Ravi,Finance,29,60000.0,3,4.0,8362,2020-07-15
3,204,Sonal,IT,27,57388.888889,5,4.066667,7000,2021-09-01
4,205,Manish,Sales,35,72000.0,10,4.9,12000,2018-03-12
5,206,Manish,Sales,35,72000.0,10,4.9,12000,2018-03-12
6,207,Kiran,sales,29,50000.0,4,3.2,-2000,2020-11-25
7,208,Neha,HR,26,45000.0,2,2.8,2500,2022-06-30
8,209,Aarav,Finance,40,95000.0,15,5.5,50000,2015-08-19
9,210,Riya,IT,23,57388.888889,1,5.5,1000,2023-01-05
10,211,Vikas,Marketing,30,58000.0,6,4.066667,8362,2019-04-10
11,212,Simran,HR,29,52000.0,5,4.0,4000,2020-02-14
12,213,Sameer,Finance,38,-8000.0,12,4.7,8000,2012-12-01
13,214,Divya,IT,24,51000.0,5,3.9,8362,2022-10-10
14,215,<NA>,Sales,31,61000.0,7,4.0,6000,2019-06-18
15,216,Ajay,Marketing,29,56000.0,5,3.6,4500,2020-08-09
16,217,Tina,HR,27,47000.0,3,2.1,2000,2021-01-20
17,218,Kabir,Finance,45,105000.0,20,4.8,15000,2010-05-05
18,219,Rohit,Sales,33,65000.0,8,3.0,8362,2016-07-07
19,220,Nisha,IT,26,49000.0,3,4.3,3800,2022-04-02

In [ ]:
df.rename_axis("Employee_Index", axis="index")

,Emp_ID,Name,Department,Age,Salary,Experience,Rating,Bonus,Join_Date
Employee_Index,,,,,,,,,
0,201,Ankit,IT,25,55000.0,5,4.2,5000,2022-01-10
1,202,Pooja,HR,28,48000.0,4,3.8,3000,2021-05-20
2,203,Ravi,Finance,29,60000.0,3,4.0,8362,2020-07-15
3,204,Sonal,IT,27,57388.888889,5,4.066667,7000,2021-09-01
4,205,Manish,Sales,35,72000.0,10,4.9,12000,2018-03-12
5,206,Manish,Sales,35,72000.0,10,4.9,12000,2018-03-12
6,207,Kiran,sales,29,50000.0,4,3.2,-2000,2020-11-25
7,208,Neha,HR,26,45000.0,2,2.8,2500,2022-06-30
8,209,Aarav,Finance,40,95000.0,15,5.5,50000,2015-08-19
9,210,Riya,IT,23,57388.888889,1,5.5,1000,2023-01-05
10,211,Vikas,Marketing,30,58000.0,6,4.066667,8362,2019-04-10
11,212,Simran,HR,29,52000.0,5,4.0,4000,2020-02-14
12,213,Sameer,Finance,38,-8000.0,12,4.7,8000,2012-12-01
13,214,Divya,IT,24,51000.0,5,3.9,8362,2022-10-10
14,215,<NA>,Sales,31,61000.0,7,4.0,6000,2019-06-18
15,216,Ajay,Marketing,29,56000.0,5,3.6,4500,2020-08-09
16,217,Tina,HR,27,47000.0,3,2.1,2000,2021-01-20
17,218,Kabir,Finance,45,105000.0,20,4.8,15000,2010-05-05
18,219,Rohit,Sales,33,65000.0,8,3.0,8362,2016-07-07
19,220,Nisha,IT,26,49000.0,3,4.3,3800,2022-04-02

In [ ]:
df.set_axis(
    ["ID","Name","Dept","Age","Salary","Exp","Rating","Bonus","Date"],
    axis="columns"
)

     ID    Name       Dept  Age        Salary  Exp    Rating  Bonus       Date
0   201   Ankit         IT   25       55000.0    5       4.2   5000 2022-01-10
1   202   Pooja         HR   28       48000.0    4       3.8   3000 2021-05-20
2   203    Ravi    Finance   29       60000.0    3       4.0   8362 2020-07-15
3   204   Sonal         IT   27  57388.888889    5  4.066667   7000 2021-09-01
4   205  Manish      Sales   35       72000.0   10       4.9  12000 2018-03-12
5   206  Manish      Sales   35       72000.0   10       4.9  12000 2018-03-12
6   207   Kiran      sales   29       50000.0    4       3.2  -2000 2020-11-25
7   208    Neha         HR   26       45000.0    2       2.8   2500 2022-06-30
8   209   Aarav    Finance   40       95000.0   15       5.5  50000 2015-08-19
9   210    Riya         IT   23  57388.888889    1       5.5   1000 2023-01-05
10  211   Vikas  Marketing   30       58000.0    6  4.066667   8362 2019-04-10
11  212  Simran         HR   29       52000.0    5       4.0   4000 2020-02-14
12  213  Sameer    Finance   38       -8000.0   12       4.7   8000 2012-12-01
13  214   Divya         IT   24       51000.0    5       3.9   8362 2022-10-10
14  215    <NA>      Sales   31       61000.0    7       4.0   6000 2019-06-18
15  216    Ajay  Marketing   29       56000.0    5       3.6   4500 2020-08-09
16  217    Tina         HR   27       47000.0    3       2.1   2000 2021-01-20
17  218   Kabir    Finance   45      105000.0   20       4.8  15000 2010-05-05
18  219   Rohit      Sales   33       65000.0    8       3.0   8362 2016-07-07
19  220   Nisha         IT   26       49000.0    3       4.3   3800 2022-04-02

In [ ]:
df.add_prefix("EMP_")

,EMP_Emp_ID,EMP_Name,EMP_Department,EMP_Age,EMP_Salary,EMP_Experience,EMP_Rating,EMP_Bonus,EMP_Join_Date
0,201,Ankit,IT,25,55000.0,5,4.2,5000,2022-01-10
1,202,Pooja,HR,28,48000.0,4,3.8,3000,2021-05-20
2,203,Ravi,Finance,29,60000.0,3,4.0,8362,2020-07-15
3,204,Sonal,IT,27,57388.888889,5,4.066667,7000,2021-09-01
4,205,Manish,Sales,35,72000.0,10,4.9,12000,2018-03-12
5,206,Manish,Sales,35,72000.0,10,4.9,12000,2018-03-12
6,207,Kiran,sales,29,50000.0,4,3.2,-2000,2020-11-25
7,208,Neha,HR,26,45000.0,2,2.8,2500,2022-06-30
8,209,Aarav,Finance,40,95000.0,15,5.5,50000,2015-08-19
9,210,Riya,IT,23,57388.888889,1,5.5,1000,2023-01-05
10,211,Vikas,Marketing,30,58000.0,6,4.066667,8362,2019-04-10
11,212,Simran,HR,29,52000.0,5,4.0,4000,2020-02-14
12,213,Sameer,Finance,38,-8000.0,12,4.7,8000,2012-12-01
13,214,Divya,IT,24,51000.0,5,3.9,8362,2022-10-10
14,215,<NA>,Sales,31,61000.0,7,4.0,6000,2019-06-18
15,216,Ajay,Marketing,29,56000.0,5,3.6,4500,2020-08-09
16,217,Tina,HR,27,47000.0,3,2.1,2000,2021-01-20
17,218,Kabir,Finance,45,105000.0,20,4.8,15000,2010-05-05
18,219,Rohit,Sales,33,65000.0,8,3.0,8362,2016-07-07
19,220,Nisha,IT,26,49000.0,3,4.3,3800,2022-04-02

In [ ]:
df.add_suffix("_INFO")

,Emp_ID_INFO,Name_INFO,Department_INFO,Age_INFO,Salary_INFO,Experience_INFO,Rating_INFO,Bonus_INFO,Join_Date_INFO
0,201,Ankit,IT,25,55000.0,5,4.2,5000,2022-01-10
1,202,Pooja,HR,28,48000.0,4,3.8,3000,2021-05-20
2,203,Ravi,Finance,29,60000.0,3,4.0,8362,2020-07-15
3,204,Sonal,IT,27,57388.888889,5,4.066667,7000,2021-09-01
4,205,Manish,Sales,35,72000.0,10,4.9,12000,2018-03-12
5,206,Manish,Sales,35,72000.0,10,4.9,12000,2018-03-12
6,207,Kiran,sales,29,50000.0,4,3.2,-2000,2020-11-25
7,208,Neha,HR,26,45000.0,2,2.8,2500,2022-06-30
8,209,Aarav,Finance,40,95000.0,15,5.5,50000,2015-08-19
9,210,Riya,IT,23,57388.888889,1,5.5,1000,2023-01-05
10,211,Vikas,Marketing,30,58000.0,6,4.066667,8362,2019-04-10
11,212,Simran,HR,29,52000.0,5,4.0,4000,2020-02-14
12,213,Sameer,Finance,38,-8000.0,12,4.7,8000,2012-12-01
13,214,Divya,IT,24,51000.0,5,3.9,8362,2022-10-10
14,215,<NA>,Sales,31,61000.0,7,4.0,6000,2019-06-18
15,216,Ajay,Marketing,29,56000.0,5,3.6,4500,2020-08-09
16,217,Tina,HR,27,47000.0,3,2.1,2000,2021-01-20
17,218,Kabir,Finance,45,105000.0,20,4.8,15000,2010-05-05
18,219,Rohit,Sales,33,65000.0,8,3.0,8362,2016-07-07
19,220,Nisha,IT,26,49000.0,3,4.3,3800,2022-04-02

5. Handling Incorrect / Inconsistent Data

In [ ]:
df["Salary"] = df["Salary"].replace(-8000, np.nan)
df

,Emp_ID,Name,Department,Age,Salary,Experience,Rating,Bonus,Join_Date
0,201,Ankit,IT,25,55000.0,5,4.2,5000,2022-01-10
1,202,Pooja,HR,28,48000.0,4,3.8,3000,2021-05-20
2,203,Ravi,Finance,29,60000.0,3,4.0,8362,2020-07-15
3,204,Sonal,IT,27,57388.888889,5,4.066667,7000,2021-09-01
4,205,Manish,Sales,35,72000.0,10,4.9,12000,2018-03-12
5,206,Manish,Sales,35,72000.0,10,4.9,12000,2018-03-12
6,207,Kiran,sales,29,50000.0,4,3.2,-2000,2020-11-25
7,208,Neha,HR,26,45000.0,2,2.8,2500,2022-06-30
8,209,Aarav,Finance,40,95000.0,15,5.5,50000,2015-08-19
9,210,Riya,IT,23,57388.888889,1,5.5,1000,2023-01-05
10,211,Vikas,Marketing,30,58000.0,6,4.066667,8362,2019-04-10
11,212,Simran,HR,29,52000.0,5,4.0,4000,2020-02-14
12,213,Sameer,Finance,38,<NA>,12,4.7,8000,2012-12-01
13,214,Divya,IT,24,51000.0,5,3.9,8362,2022-10-10
14,215,<NA>,Sales,31,61000.0,7,4.0,6000,2019-06-18
15,216,Ajay,Marketing,29,56000.0,5,3.6,4500,2020-08-09
16,217,Tina,HR,27,47000.0,3,2.1,2000,2021-01-20
17,218,Kabir,Finance,45,105000.0,20,4.8,15000,2010-05-05
18,219,Rohit,Sales,33,65000.0,8,3.0,8362,2016-07-07
19,220,Nisha,IT,26,49000.0,3,4.3,3800,2022-04-02

In [ ]:
df["Salary_Level"] = df["Salary"].apply(
    lambda x: "High" if x > 70000 else "Low"
)
df

,Emp_ID,Name,Department,Age,Salary,Experience,Rating,Bonus,Join_Date,Salary_Level
0,201,Ankit,IT,25,55000.0,5,4.2,5000,2022-01-10,Low
1,202,Pooja,HR,28,48000.0,4,3.8,3000,2021-05-20,Low
2,203,Ravi,Finance,29,60000.0,3,4.0,8362,2020-07-15,Low
3,204,Sonal,IT,27,57388.888889,5,4.066667,7000,2021-09-01,Low
4,205,Manish,Sales,35,72000.0,10,4.9,12000,2018-03-12,High
5,206,Manish,Sales,35,72000.0,10,4.9,12000,2018-03-12,High
6,207,Kiran,sales,29,50000.0,4,3.2,-2000,2020-11-25,Low
7,208,Neha,HR,26,45000.0,2,2.8,2500,2022-06-30,Low
8,209,Aarav,Finance,40,95000.0,15,5.5,50000,2015-08-19,High
9,210,Riya,IT,23,57388.888889,1,5.5,1000,2023-01-05,Low
10,211,Vikas,Marketing,30,58000.0,6,4.066667,8362,2019-04-10,Low
11,212,Simran,HR,29,52000.0,5,4.0,4000,2020-02-14,Low
12,213,Sameer,Finance,38,<NA>,12,4.7,8000,2012-12-01,Low
13,214,Divya,IT,24,51000.0,5,3.9,8362,2022-10-10,Low
14,215,<NA>,Sales,31,61000.0,7,4.0,6000,2019-06-18,Low
15,216,Ajay,Marketing,29,56000.0,5,3.6,4500,2020-08-09,Low
16,217,Tina,HR,27,47000.0,3,2.1,2000,2021-01-20,Low
17,218,Kabir,Finance,45,105000.0,20,4.8,15000,2010-05-05,High
18,219,Rohit,Sales,33,65000.0,8,3.0,8362,2016-07-07,Low
19,220,Nisha,IT,26,49000.0,3,4.3,3800,2022-04-02,Low

In [ ]:
df["Rating"] = df["Rating"].where(df["Rating"] <= 5, 5)
df

,Emp_ID,Name,Department,Age,Salary,Experience,Rating,Bonus,Join_Date,Salary_Level
0,201,Ankit,IT,25,55000.0,5,4.2,5000,2022-01-10,Low
1,202,Pooja,HR,28,48000.0,4,3.8,3000,2021-05-20,Low
2,203,Ravi,Finance,29,60000.0,3,4.0,8362,2020-07-15,Low
3,204,Sonal,IT,27,57388.888889,5,4.066667,7000,2021-09-01,Low
4,205,Manish,Sales,35,72000.0,10,4.9,12000,2018-03-12,High
5,206,Manish,Sales,35,72000.0,10,4.9,12000,2018-03-12,High
6,207,Kiran,sales,29,50000.0,4,3.2,-2000,2020-11-25,Low
7,208,Neha,HR,26,45000.0,2,2.8,2500,2022-06-30,Low
8,209,Aarav,Finance,40,95000.0,15,5.0,50000,2015-08-19,High
9,210,Riya,IT,23,57388.888889,1,5.0,1000,2023-01-05,Low
10,211,Vikas,Marketing,30,58000.0,6,4.066667,8362,2019-04-10,Low
11,212,Simran,HR,29,52000.0,5,4.0,4000,2020-02-14,Low
12,213,Sameer,Finance,38,<NA>,12,4.7,8000,2012-12-01,Low
13,214,Divya,IT,24,51000.0,5,3.9,8362,2022-10-10,Low
14,215,<NA>,Sales,31,61000.0,7,4.0,6000,2019-06-18,Low
15,216,Ajay,Marketing,29,56000.0,5,3.6,4500,2020-08-09,Low
16,217,Tina,HR,27,47000.0,3,2.1,2000,2021-01-20,Low
17,218,Kabir,Finance,45,105000.0,20,4.8,15000,2010-05-05,High
18,219,Rohit,Sales,33,65000.0,8,3.0,8362,2016-07-07,Low
19,220,Nisha,IT,26,49000.0,3,4.3,3800,2022-04-02,Low

In [ ]:
df["Salary"] = df["Salary"].mask(df["Salary"] < 0, np.nan)
df

,Emp_ID,Name,Department,Age,Salary,Experience,Rating,Bonus,Join_Date,Salary_Level
0,201,Ankit,IT,25,55000.0,5,4.2,5000,2022-01-10,Low
1,202,Pooja,HR,28,48000.0,4,3.8,3000,2021-05-20,Low
2,203,Ravi,Finance,29,60000.0,3,4.0,8362,2020-07-15,Low
3,204,Sonal,IT,27,57388.888889,5,4.066667,7000,2021-09-01,Low
4,205,Manish,Sales,35,72000.0,10,4.9,12000,2018-03-12,High
5,206,Manish,Sales,35,72000.0,10,4.9,12000,2018-03-12,High
6,207,Kiran,sales,29,50000.0,4,3.2,-2000,2020-11-25,Low
7,208,Neha,HR,26,45000.0,2,2.8,2500,2022-06-30,Low
8,209,Aarav,Finance,40,95000.0,15,5.0,50000,2015-08-19,High
9,210,Riya,IT,23,57388.888889,1,5.0,1000,2023-01-05,Low
10,211,Vikas,Marketing,30,58000.0,6,4.066667,8362,2019-04-10,Low
11,212,Simran,HR,29,52000.0,5,4.0,4000,2020-02-14,Low
12,213,Sameer,Finance,38,<NA>,12,4.7,8000,2012-12-01,Low
13,214,Divya,IT,24,51000.0,5,3.9,8362,2022-10-10,Low
14,215,<NA>,Sales,31,61000.0,7,4.0,6000,2019-06-18,Low
15,216,Ajay,Marketing,29,56000.0,5,3.6,4500,2020-08-09,Low
16,217,Tina,HR,27,47000.0,3,2.1,2000,2021-01-20,Low
17,218,Kabir,Finance,45,105000.0,20,4.8,15000,2010-05-05,High
18,219,Rohit,Sales,33,65000.0,8,3.0,8362,2016-07-07,Low
19,220,Nisha,IT,26,49000.0,3,4.3,3800,2022-04-02,Low

6. String Cleaning (Text Data)

In [ ]:
df["Department"] = df["Department"].str.lower()
df

,Emp_ID,Name,Department,Age,Salary,Experience,Rating,Bonus,Salary_Level
0,201,Ankit,it,25.0,55000.0,NaN,4.2,5000.0,Low
1,202,Pooja,hr,28.0,48000.0,4.0,3.8,3000.0,Low
2,203,Ravi,finance,NaN,60000.0,3.0,4.0,NaN,Low
3,204,Sonal,it,27.0,NaN,5.0,5.0,7000.0,Low
4,205,Manish,sales,35.0,72000.0,10.0,4.9,12000.0,High
5,206,Manish,sales,35.0,72000.0,10.0,4.9,12000.0,High
6,207,Kiran,sales,29.0,50000.0,4.0,3.2,-2000.0,Low
7,208,Neha,hr,26.0,45000.0,2.0,2.8,2500.0,Low
8,209,Aarav,finance,40.0,95000.0,15.0,5.0,50000.0,High
9,210,Riya,it,23.0,NaN,1.0,5.0,1000.0,Low
10,211,Vikas,marketing,30.0,58000.0,6.0,5.0,NaN,Low
11,212,Simran,hr,NaN,52000.0,5.0,4.0,4000.0,Low
12,213,Sameer,finance,38.0,NaN,12.0,4.7,8000.0,Low
13,214,Divya,it,24.0,51000.0,NaN,3.9,NaN,Low
14,215,None,sales,31.0,61000.0,7.0,4.0,6000.0,Low
15,216,Ajay,marketing,29.0,56000.0,5.0,3.6,4500.0,Low
16,217,Tina,hr,27.0,47000.0,3.0,2.1,2000.0,Low
17,218,Kabir,finance,45.0,105000.0,20.0,4.8,15000.0,High
18,219,Rohit,sales,33.0,65000.0,8.0,3.0,NaN,Low
19,220,Nisha,it,26.0,49000.0,3.0,4.3,3800.0,Low

In [ ]:
df["Department"] = df["Department"].str.upper()
df

,Emp_ID,Name,Department,Age,Salary,Experience,Rating,Bonus,Join_Date,Salary_Level
0,201,Ankit,IT,25,55000.0,5,4.2,5000,2022-01-10,Low
1,202,Pooja,HR,28,48000.0,4,3.8,3000,2021-05-20,Low
2,203,Ravi,FINANCE,29,60000.0,3,4.0,8362,2020-07-15,Low
3,204,Sonal,IT,27,57388.888889,5,4.066667,7000,2021-09-01,Low
4,205,Manish,SALES,35,72000.0,10,4.9,12000,2018-03-12,High
5,206,Manish,SALES,35,72000.0,10,4.9,12000,2018-03-12,High
6,207,Kiran,SALES,29,50000.0,4,3.2,-2000,2020-11-25,Low
7,208,Neha,HR,26,45000.0,2,2.8,2500,2022-06-30,Low
8,209,Aarav,FINANCE,40,95000.0,15,5.0,50000,2015-08-19,High
9,210,Riya,IT,23,57388.888889,1,5.0,1000,2023-01-05,Low
10,211,Vikas,MARKETING,30,58000.0,6,4.066667,8362,2019-04-10,Low
11,212,Simran,HR,29,52000.0,5,4.0,4000,2020-02-14,Low
12,213,Sameer,FINANCE,38,<NA>,12,4.7,8000,2012-12-01,Low
13,214,Divya,IT,24,51000.0,5,3.9,8362,2022-10-10,Low
14,215,<NA>,SALES,31,61000.0,7,4.0,6000,2019-06-18,Low
15,216,Ajay,MARKETING,29,56000.0,5,3.6,4500,2020-08-09,Low
16,217,Tina,HR,27,47000.0,3,2.1,2000,2021-01-20,Low
17,218,Kabir,FINANCE,45,105000.0,20,4.8,15000,2010-05-05,High
18,219,Rohit,SALES,33,65000.0,8,3.0,8362,2016-07-07,Low
19,220,Nisha,IT,26,49000.0,3,4.3,3800,2022-04-02,Low

In [ ]:
df["Name"] = df["Name"].str.title()
df

,Emp_ID,Name,Department,Age,Salary,Experience,Rating,Bonus,Join_Date,Salary_Level
0,201,Ankit,IT,25,55000.0,5,4.2,5000,2022-01-10,Low
1,202,Pooja,HR,28,48000.0,4,3.8,3000,2021-05-20,Low
2,203,Ravi,FINANCE,29,60000.0,3,4.0,8362,2020-07-15,Low
3,204,Sonal,IT,27,57388.888889,5,4.066667,7000,2021-09-01,Low
4,205,Manish,SALES,35,72000.0,10,4.9,12000,2018-03-12,High
5,206,Manish,SALES,35,72000.0,10,4.9,12000,2018-03-12,High
6,207,Kiran,SALES,29,50000.0,4,3.2,-2000,2020-11-25,Low
7,208,Neha,HR,26,45000.0,2,2.8,2500,2022-06-30,Low
8,209,Aarav,FINANCE,40,95000.0,15,5.0,50000,2015-08-19,High
9,210,Riya,IT,23,57388.888889,1,5.0,1000,2023-01-05,Low
10,211,Vikas,MARKETING,30,58000.0,6,4.066667,8362,2019-04-10,Low
11,212,Simran,HR,29,52000.0,5,4.0,4000,2020-02-14,Low
12,213,Sameer,FINANCE,38,<NA>,12,4.7,8000,2012-12-01,Low
13,214,Divya,IT,24,51000.0,5,3.9,8362,2022-10-10,Low
14,215,<NA>,SALES,31,61000.0,7,4.0,6000,2019-06-18,Low
15,216,Ajay,MARKETING,29,56000.0,5,3.6,4500,2020-08-09,Low
16,217,Tina,HR,27,47000.0,3,2.1,2000,2021-01-20,Low
17,218,Kabir,FINANCE,45,105000.0,20,4.8,15000,2010-05-05,High
18,219,Rohit,SALES,33,65000.0,8,3.0,8362,2016-07-07,Low
19,220,Nisha,IT,26,49000.0,3,4.3,3800,2022-04-02,Low

In [ ]:
df["Department"] = df["Department"].str.replace("IT", "Information Technology")
df

,Emp_ID,Name,Department,Age,Salary,Experience,Rating,Bonus,Join_Date,Salary_Level
0,201,Ankit,Information Technology,25,55000.0,5,4.2,5000,2022-01-10,Low
1,202,Pooja,HR,28,48000.0,4,3.8,3000,2021-05-20,Low
2,203,Ravi,FINANCE,29,60000.0,3,4.0,8362,2020-07-15,Low
3,204,Sonal,Information Technology,27,57388.888889,5,4.066667,7000,2021-09-01,Low
4,205,Manish,SALES,35,72000.0,10,4.9,12000,2018-03-12,High
5,206,Manish,SALES,35,72000.0,10,4.9,12000,2018-03-12,High
6,207,Kiran,SALES,29,50000.0,4,3.2,-2000,2020-11-25,Low
7,208,Neha,HR,26,45000.0,2,2.8,2500,2022-06-30,Low
8,209,Aarav,FINANCE,40,95000.0,15,5.0,50000,2015-08-19,High
9,210,Riya,Information Technology,23,57388.888889,1,5.0,1000,2023-01-05,Low
10,211,Vikas,MARKETING,30,58000.0,6,4.066667,8362,2019-04-10,Low
11,212,Simran,HR,29,52000.0,5,4.0,4000,2020-02-14,Low
12,213,Sameer,FINANCE,38,<NA>,12,4.7,8000,2012-12-01,Low
13,214,Divya,Information Technology,24,51000.0,5,3.9,8362,2022-10-10,Low
14,215,<NA>,SALES,31,61000.0,7,4.0,6000,2019-06-18,Low
15,216,Ajay,MARKETING,29,56000.0,5,3.6,4500,2020-08-09,Low
16,217,Tina,HR,27,47000.0,3,2.1,2000,2021-01-20,Low
17,218,Kabir,FINANCE,45,105000.0,20,4.8,15000,2010-05-05,High
18,219,Rohit,SALES,33,65000.0,8,3.0,8362,2016-07-07,Low
19,220,Nisha,Information Technology,26,49000.0,3,4.3,3800,2022-04-02,Low

In [ ]:
df["Is_IT"] = df["Department"].str.contains("IT", case=False, na=False)
df

,Emp_ID,Name,Department,Age,Salary,Experience,Rating,Bonus,Join_Date,Salary_Level,Is_IT
0,201,Ankit,Information Technology,25,55000.0,5,4.2,5000,2022-01-10,Low,False
1,202,Pooja,HR,28,48000.0,4,3.8,3000,2021-05-20,Low,False
2,203,Ravi,FINANCE,29,60000.0,3,4.0,8362,2020-07-15,Low,False
3,204,Sonal,Information Technology,27,57388.888889,5,4.066667,7000,2021-09-01,Low,False
4,205,Manish,SALES,35,72000.0,10,4.9,12000,2018-03-12,High,False
5,206,Manish,SALES,35,72000.0,10,4.9,12000,2018-03-12,High,False
6,207,Kiran,SALES,29,50000.0,4,3.2,-2000,2020-11-25,Low,False
7,208,Neha,HR,26,45000.0,2,2.8,2500,2022-06-30,Low,False
8,209,Aarav,FINANCE,40,95000.0,15,5.0,50000,2015-08-19,High,False
9,210,Riya,Information Technology,23,57388.888889,1,5.0,1000,2023-01-05,Low,False
10,211,Vikas,MARKETING,30,58000.0,6,4.066667,8362,2019-04-10,Low,False
11,212,Simran,HR,29,52000.0,5,4.0,4000,2020-02-14,Low,False
12,213,Sameer,FINANCE,38,<NA>,12,4.7,8000,2012-12-01,Low,False
13,214,Divya,Information Technology,24,51000.0,5,3.9,8362,2022-10-10,Low,False
14,215,<NA>,SALES,31,61000.0,7,4.0,6000,2019-06-18,Low,False
15,216,Ajay,MARKETING,29,56000.0,5,3.6,4500,2020-08-09,Low,False
16,217,Tina,HR,27,47000.0,3,2.1,2000,2021-01-20,Low,False
17,218,Kabir,FINANCE,45,105000.0,20,4.8,15000,2010-05-05,High,False
18,219,Rohit,SALES,33,65000.0,8,3.0,8362,2016-07-07,Low,False
19,220,Nisha,Information Technology,26,49000.0,3,4.3,3800,2022-04-02,Low,False

In [ ]:
df["First_Name"] = df["Name"].str.split().str[0]
df

,Emp_ID,Name,Department,Age,Salary,Experience,Rating,Bonus,Join_Date,Salary_Level,Is_IT,First_Name
0,201,Ankit,Information Technology,25,55000.0,5,4.2,5000,2022-01-10,Low,False,Ankit
1,202,Pooja,HR,28,48000.0,4,3.8,3000,2021-05-20,Low,False,Pooja
2,203,Ravi,FINANCE,29,60000.0,3,4.0,8362,2020-07-15,Low,False,Ravi
3,204,Sonal,Information Technology,27,57388.888889,5,4.066667,7000,2021-09-01,Low,False,Sonal
4,205,Manish,SALES,35,72000.0,10,4.9,12000,2018-03-12,High,False,Manish
5,206,Manish,SALES,35,72000.0,10,4.9,12000,2018-03-12,High,False,Manish
6,207,Kiran,SALES,29,50000.0,4,3.2,-2000,2020-11-25,Low,False,Kiran
7,208,Neha,HR,26,45000.0,2,2.8,2500,2022-06-30,Low,False,Neha
8,209,Aarav,FINANCE,40,95000.0,15,5.0,50000,2015-08-19,High,False,Aarav
9,210,Riya,Information Technology,23,57388.888889,1,5.0,1000,2023-01-05,Low,False,Riya
10,211,Vikas,MARKETING,30,58000.0,6,4.066667,8362,2019-04-10,Low,False,Vikas
11,212,Simran,HR,29,52000.0,5,4.0,4000,2020-02-14,Low,False,Simran
12,213,Sameer,FINANCE,38,<NA>,12,4.7,8000,2012-12-01,Low,False,Sameer
13,214,Divya,Information Technology,24,51000.0,5,3.9,8362,2022-10-10,Low,False,Divya
14,215,<NA>,SALES,31,61000.0,7,4.0,6000,2019-06-18,Low,False,<NA>
15,216,Ajay,MARKETING,29,56000.0,5,3.6,4500,2020-08-09,Low,False,Ajay
16,217,Tina,HR,27,47000.0,3,2.1,2000,2021-01-20,Low,False,Tina
17,218,Kabir,FINANCE,45,105000.0,20,4.8,15000,2010-05-05,High,False,Kabir
18,219,Rohit,SALES,33,65000.0,8,3.0,8362,2016-07-07,Low,False,Rohit
19,220,Nisha,Information Technology,26,49000.0,3,4.3,3800,2022-04-02,Low,False,Nisha

In [ ]:
df["Name_Length"] = df["Name"].str.len()
df

,Emp_ID,Name,Department,Age,Salary,Experience,Rating,Bonus,Join_Date,Salary_Level,Is_IT,First_Name,Name_Length
0,201,Ankit,Information Technology,25,55000.0,5,4.2,5000,2022-01-10,Low,False,Ankit,5
1,202,Pooja,HR,28,48000.0,4,3.8,3000,2021-05-20,Low,False,Pooja,5
2,203,Ravi,FINANCE,29,60000.0,3,4.0,8362,2020-07-15,Low,False,Ravi,4
3,204,Sonal,Information Technology,27,57388.888889,5,4.066667,7000,2021-09-01,Low,False,Sonal,5
4,205,Manish,SALES,35,72000.0,10,4.9,12000,2018-03-12,High,False,Manish,6
5,206,Manish,SALES,35,72000.0,10,4.9,12000,2018-03-12,High,False,Manish,6
6,207,Kiran,SALES,29,50000.0,4,3.2,-2000,2020-11-25,Low,False,Kiran,5
7,208,Neha,HR,26,45000.0,2,2.8,2500,2022-06-30,Low,False,Neha,4
8,209,Aarav,FINANCE,40,95000.0,15,5.0,50000,2015-08-19,High,False,Aarav,5
9,210,Riya,Information Technology,23,57388.888889,1,5.0,1000,2023-01-05,Low,False,Riya,4
10,211,Vikas,MARKETING,30,58000.0,6,4.066667,8362,2019-04-10,Low,False,Vikas,5
11,212,Simran,HR,29,52000.0,5,4.0,4000,2020-02-14,Low,False,Simran,6
12,213,Sameer,FINANCE,38,<NA>,12,4.7,8000,2012-12-01,Low,False,Sameer,6
13,214,Divya,Information Technology,24,51000.0,5,3.9,8362,2022-10-10,Low,False,Divya,5
14,215,<NA>,SALES,31,61000.0,7,4.0,6000,2019-06-18,Low,False,<NA>,<NA>
15,216,Ajay,MARKETING,29,56000.0,5,3.6,4500,2020-08-09,Low,False,Ajay,4
16,217,Tina,HR,27,47000.0,3,2.1,2000,2021-01-20,Low,False,Tina,4
17,218,Kabir,FINANCE,45,105000.0,20,4.8,15000,2010-05-05,High,False,Kabir,5
18,219,Rohit,SALES,33,65000.0,8,3.0,8362,2016-07-07,Low,False,Rohit,5
19,220,Nisha,Information Technology,26,49000.0,3,4.3,3800,2022-04-02,Low,False,Nisha,5

7. Handling Outliers (Numeric Data)

In [ ]:
df.describe()

,Emp_ID,Age,Salary,Experience,Rating,Bonus,Join_Date,Name_Length
count,20.0,20.0,19.0,20.0,20.0,20.0,20,19.0
mean,210.5,30.45,60830.409357,6.65,4.016667,8362.4,2019-06-20 09:36:00,4.947368
min,201.0,23.0,45000.0,1.0,2.1,-2000.0,2010-05-05 00:00:00,4.0
25%,205.75,26.75,50500.0,3.75,3.75,3600.0,2018-03-12 00:00:00,4.5
50%,210.5,29.0,57388.888889,5.0,4.033333,6500.0,2020-07-27 12:00:00,5.0
75%,215.25,33.5,63000.0,8.5,4.725,8362.0,2021-10-03 18:00:00,5.0
max,220.0,45.0,105000.0,20.0,5.0,50000.0,2023-01-05 00:00:00,6.0
std,5.91608,5.679835,15835.146893,4.715875,0.787512,10620.331794,NaN,0.705036

In [ ]:
df["Salary"].quantile(0.25)
df["Salary"].quantile(0.75)

np.float64(63000.0)

In [ ]:
df["Bonus"] = df["Bonus"].clip(0, 10000)
df

,Emp_ID,Name,Department,Age,Salary,Experience,Rating,Bonus,Join_Date,Salary_Level,Is_IT,First_Name,Name_Length
0,201,Ankit,Information Technology,25,55000.0,5,4.2,5000,2022-01-10,Low,False,Ankit,5
1,202,Pooja,HR,28,48000.0,4,3.8,3000,2021-05-20,Low,False,Pooja,5
2,203,Ravi,FINANCE,29,60000.0,3,4.0,8362,2020-07-15,Low,False,Ravi,4
3,204,Sonal,Information Technology,27,57388.888889,5,4.066667,7000,2021-09-01,Low,False,Sonal,5
4,205,Manish,SALES,35,72000.0,10,4.9,10000,2018-03-12,High,False,Manish,6
5,206,Manish,SALES,35,72000.0,10,4.9,10000,2018-03-12,High,False,Manish,6
6,207,Kiran,SALES,29,50000.0,4,3.2,0,2020-11-25,Low,False,Kiran,5
7,208,Neha,HR,26,45000.0,2,2.8,2500,2022-06-30,Low,False,Neha,4
8,209,Aarav,FINANCE,40,95000.0,15,5.0,10000,2015-08-19,High,False,Aarav,5
9,210,Riya,Information Technology,23,57388.888889,1,5.0,1000,2023-01-05,Low,False,Riya,4
10,211,Vikas,MARKETING,30,58000.0,6,4.066667,8362,2019-04-10,Low,False,Vikas,5
11,212,Simran,HR,29,52000.0,5,4.0,4000,2020-02-14,Low,False,Simran,6
12,213,Sameer,FINANCE,38,<NA>,12,4.7,8000,2012-12-01,Low,False,Sameer,6
13,214,Divya,Information Technology,24,51000.0,5,3.9,8362,2022-10-10,Low,False,Divya,5
14,215,<NA>,SALES,31,61000.0,7,4.0,6000,2019-06-18,Low,False,<NA>,<NA>
15,216,Ajay,MARKETING,29,56000.0,5,3.6,4500,2020-08-09,Low,False,Ajay,4
16,217,Tina,HR,27,47000.0,3,2.1,2000,2021-01-20,Low,False,Tina,4
17,218,Kabir,FINANCE,45,105000.0,20,4.8,10000,2010-05-05,High,False,Kabir,5
18,219,Rohit,SALES,33,65000.0,8,3.0,8362,2016-07-07,Low,False,Rohit,5
19,220,Nisha,Information Technology,26,49000.0,3,4.3,3800,2022-04-02,Low,False,Nisha,5

In [ ]:
df["Valid_Salary"] = df["Salary"].between(20000, 100000)
df

,Emp_ID,Name,Department,Age,Salary,Experience,Rating,Bonus,Join_Date,Salary_Level,Is_IT,First_Name,Name_Length,Valid_Salary
0,201,Ankit,Information Technology,25,55000.0,5,4.2,5000,2022-01-10,Low,False,Ankit,5,True
1,202,Pooja,HR,28,48000.0,4,3.8,3000,2021-05-20,Low,False,Pooja,5,True
2,203,Ravi,FINANCE,29,60000.0,3,4.0,8362,2020-07-15,Low,False,Ravi,4,True
3,204,Sonal,Information Technology,27,57388.888889,5,4.066667,7000,2021-09-01,Low,False,Sonal,5,True
4,205,Manish,SALES,35,72000.0,10,4.9,10000,2018-03-12,High,False,Manish,6,True
5,206,Manish,SALES,35,72000.0,10,4.9,10000,2018-03-12,High,False,Manish,6,True
6,207,Kiran,SALES,29,50000.0,4,3.2,0,2020-11-25,Low,False,Kiran,5,True
7,208,Neha,HR,26,45000.0,2,2.8,2500,2022-06-30,Low,False,Neha,4,True
8,209,Aarav,FINANCE,40,95000.0,15,5.0,10000,2015-08-19,High,False,Aarav,5,True
9,210,Riya,Information Technology,23,57388.888889,1,5.0,1000,2023-01-05,Low,False,Riya,4,True
10,211,Vikas,MARKETING,30,58000.0,6,4.066667,8362,2019-04-10,Low,False,Vikas,5,True
11,212,Simran,HR,29,52000.0,5,4.0,4000,2020-02-14,Low,False,Simran,6,True
12,213,Sameer,FINANCE,38,<NA>,12,4.7,8000,2012-12-01,Low,False,Sameer,6,<NA>
13,214,Divya,Information Technology,24,51000.0,5,3.9,8362,2022-10-10,Low,False,Divya,5,True
14,215,<NA>,SALES,31,61000.0,7,4.0,6000,2019-06-18,Low,False,<NA>,<NA>,True
15,216,Ajay,MARKETING,29,56000.0,5,3.6,4500,2020-08-09,Low,False,Ajay,4,True
16,217,Tina,HR,27,47000.0,3,2.1,2000,2021-01-20,Low,False,Tina,4,True
17,218,Kabir,FINANCE,45,105000.0,20,4.8,10000,2010-05-05,High,False,Kabir,5,False
18,219,Rohit,SALES,33,65000.0,8,3.0,8362,2016-07-07,Low,False,Rohit,5,True
19,220,Nisha,Information Technology,26,49000.0,3,4.3,3800,2022-04-02,Low,False,Nisha,5,True

8. Index & Row Operations

In [ ]:
df.reset_index()

,index,Emp_ID,Name,Department,Age,Salary,Experience,Rating,Bonus,Join_Date,Salary_Level,Is_IT,First_Name,Name_Length,Valid_Salary
0,0,201,Ankit,Information Technology,25,55000.0,5,4.2,5000,2022-01-10,Low,False,Ankit,5,True
1,1,202,Pooja,HR,28,48000.0,4,3.8,3000,2021-05-20,Low,False,Pooja,5,True
2,2,203,Ravi,FINANCE,29,60000.0,3,4.0,8362,2020-07-15,Low,False,Ravi,4,True
3,3,204,Sonal,Information Technology,27,57388.888889,5,4.066667,7000,2021-09-01,Low,False,Sonal,5,True
4,4,205,Manish,SALES,35,72000.0,10,4.9,10000,2018-03-12,High,False,Manish,6,True
5,5,206,Manish,SALES,35,72000.0,10,4.9,10000,2018-03-12,High,False,Manish,6,True
6,6,207,Kiran,SALES,29,50000.0,4,3.2,0,2020-11-25,Low,False,Kiran,5,True
7,7,208,Neha,HR,26,45000.0,2,2.8,2500,2022-06-30,Low,False,Neha,4,True
8,8,209,Aarav,FINANCE,40,95000.0,15,5.0,10000,2015-08-19,High,False,Aarav,5,True
9,9,210,Riya,Information Technology,23,57388.888889,1,5.0,1000,2023-01-05,Low,False,Riya,4,True
10,10,211,Vikas,MARKETING,30,58000.0,6,4.066667,8362,2019-04-10,Low,False,Vikas,5,True
11,11,212,Simran,HR,29,52000.0,5,4.0,4000,2020-02-14,Low,False,Simran,6,True
12,12,213,Sameer,FINANCE,38,<NA>,12,4.7,8000,2012-12-01,Low,False,Sameer,6,<NA>
13,13,214,Divya,Information Technology,24,51000.0,5,3.9,8362,2022-10-10,Low,False,Divya,5,True
14,14,215,<NA>,SALES,31,61000.0,7,4.0,6000,2019-06-18,Low,False,<NA>,<NA>,True
15,15,216,Ajay,MARKETING,29,56000.0,5,3.6,4500,2020-08-09,Low,False,Ajay,4,True
16,16,217,Tina,HR,27,47000.0,3,2.1,2000,2021-01-20,Low,False,Tina,4,True
17,17,218,Kabir,FINANCE,45,105000.0,20,4.8,10000,2010-05-05,High,False,Kabir,5,False
18,18,219,Rohit,SALES,33,65000.0,8,3.0,8362,2016-07-07,Low,False,Rohit,5,True
19,19,220,Nisha,Information Technology,26,49000.0,3,4.3,3800,2022-04-02,Low,False,Nisha,5,True

In [ ]:
df.set_index("Emp_ID", inplace=True)

In [ ]:
df.sort_index()

,Name,Department,Age,Salary,Experience,Rating,Bonus,Join_Date,Salary_Level,Is_IT,First_Name,Name_Length,Valid_Salary
Emp_ID,,,,,,,,,,,,,
201,Ankit,Information Technology,25,55000.0,5,4.2,5000,2022-01-10,Low,False,Ankit,5,True
202,Pooja,HR,28,48000.0,4,3.8,3000,2021-05-20,Low,False,Pooja,5,True
203,Ravi,FINANCE,29,60000.0,3,4.0,8362,2020-07-15,Low,False,Ravi,4,True
204,Sonal,Information Technology,27,57388.888889,5,4.066667,7000,2021-09-01,Low,False,Sonal,5,True
205,Manish,SALES,35,72000.0,10,4.9,10000,2018-03-12,High,False,Manish,6,True
206,Manish,SALES,35,72000.0,10,4.9,10000,2018-03-12,High,False,Manish,6,True
207,Kiran,SALES,29,50000.0,4,3.2,0,2020-11-25,Low,False,Kiran,5,True
208,Neha,HR,26,45000.0,2,2.8,2500,2022-06-30,Low,False,Neha,4,True
209,Aarav,FINANCE,40,95000.0,15,5.0,10000,2015-08-19,High,False,Aarav,5,True
210,Riya,Information Technology,23,57388.888889,1,5.0,1000,2023-01-05,Low,False,Riya,4,True
211,Vikas,MARKETING,30,58000.0,6,4.066667,8362,2019-04-10,Low,False,Vikas,5,True
212,Simran,HR,29,52000.0,5,4.0,4000,2020-02-14,Low,False,Simran,6,True
213,Sameer,FINANCE,38,<NA>,12,4.7,8000,2012-12-01,Low,False,Sameer,6,<NA>
214,Divya,Information Technology,24,51000.0,5,3.9,8362,2022-10-10,Low,False,Divya,5,True
215,<NA>,SALES,31,61000.0,7,4.0,6000,2019-06-18,Low,False,<NA>,<NA>,True
216,Ajay,MARKETING,29,56000.0,5,3.6,4500,2020-08-09,Low,False,Ajay,4,True
217,Tina,HR,27,47000.0,3,2.1,2000,2021-01-20,Low,False,Tina,4,True
218,Kabir,FINANCE,45,105000.0,20,4.8,10000,2010-05-05,High,False,Kabir,5,False
219,Rohit,SALES,33,65000.0,8,3.0,8362,2016-07-07,Low,False,Rohit,5,True
220,Nisha,Information Technology,26,49000.0,3,4.3,3800,2022-04-02,Low,False,Nisha,5,True

9. Sorting & Filtering Data

In [ ]:
df.sort_values(by="Salary")

,Name,Department,Age,Salary,Experience,Rating,Bonus,Join_Date,Salary_Level,Is_IT,First_Name,Name_Length,Valid_Salary
Emp_ID,,,,,,,,,,,,,
208,Neha,HR,26,45000.0,2,2.8,2500,2022-06-30,Low,False,Neha,4,True
217,Tina,HR,27,47000.0,3,2.1,2000,2021-01-20,Low,False,Tina,4,True
202,Pooja,HR,28,48000.0,4,3.8,3000,2021-05-20,Low,False,Pooja,5,True
220,Nisha,Information Technology,26,49000.0,3,4.3,3800,2022-04-02,Low,False,Nisha,5,True
207,Kiran,SALES,29,50000.0,4,3.2,0,2020-11-25,Low,False,Kiran,5,True
214,Divya,Information Technology,24,51000.0,5,3.9,8362,2022-10-10,Low,False,Divya,5,True
212,Simran,HR,29,52000.0,5,4.0,4000,2020-02-14,Low,False,Simran,6,True
201,Ankit,Information Technology,25,55000.0,5,4.2,5000,2022-01-10,Low,False,Ankit,5,True
216,Ajay,MARKETING,29,56000.0,5,3.6,4500,2020-08-09,Low,False,Ajay,4,True
210,Riya,Information Technology,23,57388.888889,1,5.0,1000,2023-01-05,Low,False,Riya,4,True
204,Sonal,Information Technology,27,57388.888889,5,4.066667,7000,2021-09-01,Low,False,Sonal,5,True
211,Vikas,MARKETING,30,58000.0,6,4.066667,8362,2019-04-10,Low,False,Vikas,5,True
203,Ravi,FINANCE,29,60000.0,3,4.0,8362,2020-07-15,Low,False,Ravi,4,True
215,<NA>,SALES,31,61000.0,7,4.0,6000,2019-06-18,Low,False,<NA>,<NA>,True
219,Rohit,SALES,33,65000.0,8,3.0,8362,2016-07-07,Low,False,Rohit,5,True
206,Manish,SALES,35,72000.0,10,4.9,10000,2018-03-12,High,False,Manish,6,True
205,Manish,SALES,35,72000.0,10,4.9,10000,2018-03-12,High,False,Manish,6,True
209,Aarav,FINANCE,40,95000.0,15,5.0,10000,2015-08-19,High,False,Aarav,5,True
218,Kabir,FINANCE,45,105000.0,20,4.8,10000,2010-05-05,High,False,Kabir,5,False
213,Sameer,FINANCE,38,<NA>,12,4.7,8000,2012-12-01,Low,False,Sameer,6,<NA>

In [ ]:
df.query("Salary > 60000")

/tmp/ipython-input-3423322952.py:1: RuntimeWarning: Engine has switched to 'python' because numexpr does not support extension array dtypes. Please set your engine to python manually.
  df.query("Salary > 60000")

,Name,Department,Age,Salary,Experience,Rating,Bonus,Join_Date,Salary_Level,Is_IT,First_Name,Name_Length,Valid_Salary
Emp_ID,,,,,,,,,,,,,
205,Manish,SALES,35,72000.0,10,4.9,10000,2018-03-12,High,False,Manish,6,True
206,Manish,SALES,35,72000.0,10,4.9,10000,2018-03-12,High,False,Manish,6,True
209,Aarav,FINANCE,40,95000.0,15,5.0,10000,2015-08-19,High,False,Aarav,5,True
215,<NA>,SALES,31,61000.0,7,4.0,6000,2019-06-18,Low,False,<NA>,<NA>,True
218,Kabir,FINANCE,45,105000.0,20,4.8,10000,2010-05-05,High,False,Kabir,5,False
219,Rohit,SALES,33,65000.0,8,3.0,8362,2016-07-07,Low,False,Rohit,5,True

In [ ]:
df.loc[201]

Name                             Ankit
Department      Information Technology
Age                                 25
Salary                         55000.0
Experience                           5
Rating                             4.2
Bonus                             5000
Join_Date          2022-01-10 00:00:00
Salary_Level                       Low
Is_IT                            False
First_Name                       Ankit
Name_Length                          5
Valid_Salary                      True
Name: 201, dtype: object

In [ ]:
df.iloc[0:5, 1:4]

                    Department  Age        Salary
Emp_ID
201     Information Technology   25       55000.0
202                         HR   28       48000.0
203                    FINANCE   29       60000.0
204     Information Technology   27  57388.888889
205                      SALES   35       72000.0

In [ ]:
df.filter(items=["Name", "Salary", "Rating"])

          Name        Salary    Rating
Emp_ID
201      Ankit       55000.0       4.2
202      Pooja       48000.0       3.8
203       Ravi       60000.0       4.0
204      Sonal  57388.888889  4.066667
205     Manish       72000.0       4.9
206     Manish       72000.0       4.9
207      Kiran       50000.0       3.2
208       Neha       45000.0       2.8
209      Aarav       95000.0       5.0
210       Riya  57388.888889       5.0
211      Vikas       58000.0  4.066667
212     Simran       52000.0       4.0
213     Sameer          <NA>       4.7
214      Divya       51000.0       3.9
215       <NA>       61000.0       4.0
216       Ajay       56000.0       3.6
217       Tina       47000.0       2.1
218      Kabir      105000.0       4.8
219      Rohit       65000.0       3.0
220      Nisha       49000.0       4.3

11. Handling Categorical Data

In [ ]:
df["Department"] = df["Department"].astype("category")
df

,Name,Department,Age,Salary,Experience,Rating,Bonus,Join_Date,Salary_Level,Is_IT,First_Name,Name_Length,Valid_Salary
Emp_ID,,,,,,,,,,,,,
201,Ankit,Information Technology,25,55000.0,5,4.2,5000,2022-01-10,Low,False,Ankit,5,True
202,Pooja,HR,28,48000.0,4,3.8,3000,2021-05-20,Low,False,Pooja,5,True
203,Ravi,FINANCE,29,60000.0,3,4.0,8362,2020-07-15,Low,False,Ravi,4,True
204,Sonal,Information Technology,27,57388.888889,5,4.066667,7000,2021-09-01,Low,False,Sonal,5,True
205,Manish,SALES,35,72000.0,10,4.9,10000,2018-03-12,High,False,Manish,6,True
206,Manish,SALES,35,72000.0,10,4.9,10000,2018-03-12,High,False,Manish,6,True
207,Kiran,SALES,29,50000.0,4,3.2,0,2020-11-25,Low,False,Kiran,5,True
208,Neha,HR,26,45000.0,2,2.8,2500,2022-06-30,Low,False,Neha,4,True
209,Aarav,FINANCE,40,95000.0,15,5.0,10000,2015-08-19,High,False,Aarav,5,True
210,Riya,Information Technology,23,57388.888889,1,5.0,1000,2023-01-05,Low,False,Riya,4,True
211,Vikas,MARKETING,30,58000.0,6,4.066667,8362,2019-04-10,Low,False,Vikas,5,True
212,Simran,HR,29,52000.0,5,4.0,4000,2020-02-14,Low,False,Simran,6,True
213,Sameer,FINANCE,38,<NA>,12,4.7,8000,2012-12-01,Low,False,Sameer,6,<NA>
214,Divya,Information Technology,24,51000.0,5,3.9,8362,2022-10-10,Low,False,Divya,5,True
215,<NA>,SALES,31,61000.0,7,4.0,6000,2019-06-18,Low,False,<NA>,<NA>,True
216,Ajay,MARKETING,29,56000.0,5,3.6,4500,2020-08-09,Low,False,Ajay,4,True
217,Tina,HR,27,47000.0,3,2.1,2000,2021-01-20,Low,False,Tina,4,True
218,Kabir,FINANCE,45,105000.0,20,4.8,10000,2010-05-05,High,False,Kabir,5,False
219,Rohit,SALES,33,65000.0,8,3.0,8362,2016-07-07,Low,False,Rohit,5,True
220,Nisha,Information Technology,26,49000.0,3,4.3,3800,2022-04-02,Low,False,Nisha,5,True

In [ ]:
df["Department"].cat.categories

Index(['FINANCE', 'HR', 'Information Technology', 'MARKETING', 'SALES'], dtype='string')

In [ ]:
df["Department"] = df["Department"].cat.rename_categories({
    "Hr": "HR",
    "Information Technology": "IT"
})
df

,Name,Department,Age,Salary,Experience,Rating,Bonus,Join_Date,Salary_Level,Is_IT,First_Name,Name_Length,Valid_Salary
Emp_ID,,,,,,,,,,,,,
201,Ankit,IT,25,55000.0,5,4.2,5000,2022-01-10,Low,False,Ankit,5,True
202,Pooja,HR,28,48000.0,4,3.8,3000,2021-05-20,Low,False,Pooja,5,True
203,Ravi,FINANCE,29,60000.0,3,4.0,8362,2020-07-15,Low,False,Ravi,4,True
204,Sonal,IT,27,57388.888889,5,4.066667,7000,2021-09-01,Low,False,Sonal,5,True
205,Manish,SALES,35,72000.0,10,4.9,10000,2018-03-12,High,False,Manish,6,True
206,Manish,SALES,35,72000.0,10,4.9,10000,2018-03-12,High,False,Manish,6,True
207,Kiran,SALES,29,50000.0,4,3.2,0,2020-11-25,Low,False,Kiran,5,True
208,Neha,HR,26,45000.0,2,2.8,2500,2022-06-30,Low,False,Neha,4,True
209,Aarav,FINANCE,40,95000.0,15,5.0,10000,2015-08-19,High,False,Aarav,5,True
210,Riya,IT,23,57388.888889,1,5.0,1000,2023-01-05,Low,False,Riya,4,True
211,Vikas,MARKETING,30,58000.0,6,4.066667,8362,2019-04-10,Low,False,Vikas,5,True
212,Simran,HR,29,52000.0,5,4.0,4000,2020-02-14,Low,False,Simran,6,True
213,Sameer,FINANCE,38,<NA>,12,4.7,8000,2012-12-01,Low,False,Sameer,6,<NA>
214,Divya,IT,24,51000.0,5,3.9,8362,2022-10-10,Low,False,Divya,5,True
215,<NA>,SALES,31,61000.0,7,4.0,6000,2019-06-18,Low,False,<NA>,<NA>,True
216,Ajay,MARKETING,29,56000.0,5,3.6,4500,2020-08-09,Low,False,Ajay,4,True
217,Tina,HR,27,47000.0,3,2.1,2000,2021-01-20,Low,False,Tina,4,True
218,Kabir,FINANCE,45,105000.0,20,4.8,10000,2010-05-05,High,False,Kabir,5,False
219,Rohit,SALES,33,65000.0,8,3.0,8362,2016-07-07,Low,False,Rohit,5,True
220,Nisha,IT,26,49000.0,3,4.3,3800,2022-04-02,Low,False,Nisha,5,True

In [ ]:
df["Dept_Code"] = df["Department"].cat.codes
df

,Name,Department,Age,Salary,Experience,Rating,Bonus,Join_Date,Salary_Level,Is_IT,First_Name,Name_Length,Valid_Salary,Dept_Code
Emp_ID,,,,,,,,,,,,,,
201,Ankit,IT,25,55000.0,5,4.2,5000,2022-01-10,Low,False,Ankit,5,True,2
202,Pooja,HR,28,48000.0,4,3.8,3000,2021-05-20,Low,False,Pooja,5,True,1
203,Ravi,FINANCE,29,60000.0,3,4.0,8362,2020-07-15,Low,False,Ravi,4,True,0
204,Sonal,IT,27,57388.888889,5,4.066667,7000,2021-09-01,Low,False,Sonal,5,True,2
205,Manish,SALES,35,72000.0,10,4.9,10000,2018-03-12,High,False,Manish,6,True,4
206,Manish,SALES,35,72000.0,10,4.9,10000,2018-03-12,High,False,Manish,6,True,4
207,Kiran,SALES,29,50000.0,4,3.2,0,2020-11-25,Low,False,Kiran,5,True,4
208,Neha,HR,26,45000.0,2,2.8,2500,2022-06-30,Low,False,Neha,4,True,1
209,Aarav,FINANCE,40,95000.0,15,5.0,10000,2015-08-19,High,False,Aarav,5,True,0
210,Riya,IT,23,57388.888889,1,5.0,1000,2023-01-05,Low,False,Riya,4,True,2
211,Vikas,MARKETING,30,58000.0,6,4.066667,8362,2019-04-10,Low,False,Vikas,5,True,3
212,Simran,HR,29,52000.0,5,4.0,4000,2020-02-14,Low,False,Simran,6,True,1
213,Sameer,FINANCE,38,<NA>,12,4.7,8000,2012-12-01,Low,False,Sameer,6,<NA>,0
214,Divya,IT,24,51000.0,5,3.9,8362,2022-10-10,Low,False,Divya,5,True,2
215,<NA>,SALES,31,61000.0,7,4.0,6000,2019-06-18,Low,False,<NA>,<NA>,True,4
216,Ajay,MARKETING,29,56000.0,5,3.6,4500,2020-08-09,Low,False,Ajay,4,True,3
217,Tina,HR,27,47000.0,3,2.1,2000,2021-01-20,Low,False,Tina,4,True,1
218,Kabir,FINANCE,45,105000.0,20,4.8,10000,2010-05-05,High,False,Kabir,5,False,0
219,Rohit,SALES,33,65000.0,8,3.0,8362,2016-07-07,Low,False,Rohit,5,True,4
220,Nisha,IT,26,49000.0,3,4.3,3800,2022-04-02,Low,False,Nisha,5,True,2

13. Removing / Selecting Columns

In [ ]:
df.drop("Valid_Salary", axis=1, inplace=True)
df

,Name,Department,Age,Salary,Experience,Rating,Bonus,Join_Date,Salary_Level,Is_IT,First_Name,Name_Length,Dept_Code
Emp_ID,,,,,,,,,,,,,
201,Ankit,IT,25,55000.0,5,4.2,5000,2022-01-10,Low,False,Ankit,5,2
202,Pooja,HR,28,48000.0,4,3.8,3000,2021-05-20,Low,False,Pooja,5,1
203,Ravi,FINANCE,29,60000.0,3,4.0,8362,2020-07-15,Low,False,Ravi,4,0
204,Sonal,IT,27,57388.888889,5,4.066667,7000,2021-09-01,Low,False,Sonal,5,2
205,Manish,SALES,35,72000.0,10,4.9,10000,2018-03-12,High,False,Manish,6,4
206,Manish,SALES,35,72000.0,10,4.9,10000,2018-03-12,High,False,Manish,6,4
207,Kiran,SALES,29,50000.0,4,3.2,0,2020-11-25,Low,False,Kiran,5,4
208,Neha,HR,26,45000.0,2,2.8,2500,2022-06-30,Low,False,Neha,4,1
209,Aarav,FINANCE,40,95000.0,15,5.0,10000,2015-08-19,High,False,Aarav,5,0
210,Riya,IT,23,57388.888889,1,5.0,1000,2023-01-05,Low,False,Riya,4,2
211,Vikas,MARKETING,30,58000.0,6,4.066667,8362,2019-04-10,Low,False,Vikas,5,3
212,Simran,HR,29,52000.0,5,4.0,4000,2020-02-14,Low,False,Simran,6,1
213,Sameer,FINANCE,38,<NA>,12,4.7,8000,2012-12-01,Low,False,Sameer,6,0
214,Divya,IT,24,51000.0,5,3.9,8362,2022-10-10,Low,False,Divya,5,2
215,<NA>,SALES,31,61000.0,7,4.0,6000,2019-06-18,Low,False,<NA>,<NA>,4
216,Ajay,MARKETING,29,56000.0,5,3.6,4500,2020-08-09,Low,False,Ajay,4,3
217,Tina,HR,27,47000.0,3,2.1,2000,2021-01-20,Low,False,Tina,4,1
218,Kabir,FINANCE,45,105000.0,20,4.8,10000,2010-05-05,High,False,Kabir,5,0
219,Rohit,SALES,33,65000.0,8,3.0,8362,2016-07-07,Low,False,Rohit,5,4
220,Nisha,IT,26,49000.0,3,4.3,3800,2022-04-02,Low,False,Nisha,5,2

In [ ]:
bonus_col = df.pop("Name_Length")
df

,Name,Department,Age,Salary,Experience,Rating,Bonus,Join_Date,Salary_Level,Is_IT,First_Name,Dept_Code
Emp_ID,,,,,,,,,,,,
201,Ankit,IT,25,55000.0,5,4.2,5000,2022-01-10,Low,False,Ankit,2
202,Pooja,HR,28,48000.0,4,3.8,3000,2021-05-20,Low,False,Pooja,1
203,Ravi,FINANCE,29,60000.0,3,4.0,8362,2020-07-15,Low,False,Ravi,0
204,Sonal,IT,27,57388.888889,5,4.066667,7000,2021-09-01,Low,False,Sonal,2
205,Manish,SALES,35,72000.0,10,4.9,10000,2018-03-12,High,False,Manish,4
206,Manish,SALES,35,72000.0,10,4.9,10000,2018-03-12,High,False,Manish,4
207,Kiran,SALES,29,50000.0,4,3.2,0,2020-11-25,Low,False,Kiran,4
208,Neha,HR,26,45000.0,2,2.8,2500,2022-06-30,Low,False,Neha,1
209,Aarav,FINANCE,40,95000.0,15,5.0,10000,2015-08-19,High,False,Aarav,0
210,Riya,IT,23,57388.888889,1,5.0,1000,2023-01-05,Low,False,Riya,2
211,Vikas,MARKETING,30,58000.0,6,4.066667,8362,2019-04-10,Low,False,Vikas,3
212,Simran,HR,29,52000.0,5,4.0,4000,2020-02-14,Low,False,Simran,1
213,Sameer,FINANCE,38,<NA>,12,4.7,8000,2012-12-01,Low,False,Sameer,0
214,Divya,IT,24,51000.0,5,3.9,8362,2022-10-10,Low,False,Divya,2
215,<NA>,SALES,31,61000.0,7,4.0,6000,2019-06-18,Low,False,<NA>,4
216,Ajay,MARKETING,29,56000.0,5,3.6,4500,2020-08-09,Low,False,Ajay,3
217,Tina,HR,27,47000.0,3,2.1,2000,2021-01-20,Low,False,Tina,1
218,Kabir,FINANCE,45,105000.0,20,4.8,10000,2010-05-05,High,False,Kabir,0
219,Rohit,SALES,33,65000.0,8,3.0,8362,2016-07-07,Low,False,Rohit,4
220,Nisha,IT,26,49000.0,3,4.3,3800,2022-04-02,Low,False,Nisha,2

12. Handling Date & Time Data

In [ ]:
df["Join_Date"] = pd.to_datetime(df["Join_Date"])
df

,Name,Department,Age,Salary,Experience,Rating,Bonus,Join_Date,Salary_Level,Is_IT,First_Name,Dept_Code
Emp_ID,,,,,,,,,,,,
201,Ankit,IT,25,55000.0,5,4.2,5000,2022-01-10,Low,False,Ankit,2
202,Pooja,HR,28,48000.0,4,3.8,3000,2021-05-20,Low,False,Pooja,1
203,Ravi,FINANCE,29,60000.0,3,4.0,8362,2020-07-15,Low,False,Ravi,0
204,Sonal,IT,27,57388.888889,5,4.066667,7000,2021-09-01,Low,False,Sonal,2
205,Manish,SALES,35,72000.0,10,4.9,10000,2018-03-12,High,False,Manish,4
206,Manish,SALES,35,72000.0,10,4.9,10000,2018-03-12,High,False,Manish,4
207,Kiran,SALES,29,50000.0,4,3.2,0,2020-11-25,Low,False,Kiran,4
208,Neha,HR,26,45000.0,2,2.8,2500,2022-06-30,Low,False,Neha,1
209,Aarav,FINANCE,40,95000.0,15,5.0,10000,2015-08-19,High,False,Aarav,0
210,Riya,IT,23,57388.888889,1,5.0,1000,2023-01-05,Low,False,Riya,2
211,Vikas,MARKETING,30,58000.0,6,4.066667,8362,2019-04-10,Low,False,Vikas,3
212,Simran,HR,29,52000.0,5,4.0,4000,2020-02-14,Low,False,Simran,1
213,Sameer,FINANCE,38,<NA>,12,4.7,8000,2012-12-01,Low,False,Sameer,0
214,Divya,IT,24,51000.0,5,3.9,8362,2022-10-10,Low,False,Divya,2
215,<NA>,SALES,31,61000.0,7,4.0,6000,2019-06-18,Low,False,<NA>,4
216,Ajay,MARKETING,29,56000.0,5,3.6,4500,2020-08-09,Low,False,Ajay,3
217,Tina,HR,27,47000.0,3,2.1,2000,2021-01-20,Low,False,Tina,1
218,Kabir,FINANCE,45,105000.0,20,4.8,10000,2010-05-05,High,False,Kabir,0
219,Rohit,SALES,33,65000.0,8,3.0,8362,2016-07-07,Low,False,Rohit,4
220,Nisha,IT,26,49000.0,3,4.3,3800,2022-04-02,Low,False,Nisha,2

In [ ]:
df["Join_Year"] = df["Join_Date"].dt.year
df

,Name,Department,Age,Salary,Experience,Rating,Bonus,Join_Date,Salary_Level,Is_IT,First_Name,Dept_Code,Join_Year
Emp_ID,,,,,,,,,,,,,
201,Ankit,IT,25,55000.0,5,4.2,5000,2022-01-10,Low,False,Ankit,2,2022
202,Pooja,HR,28,48000.0,4,3.8,3000,2021-05-20,Low,False,Pooja,1,2021
203,Ravi,FINANCE,29,60000.0,3,4.0,8362,2020-07-15,Low,False,Ravi,0,2020
204,Sonal,IT,27,57388.888889,5,4.066667,7000,2021-09-01,Low,False,Sonal,2,2021
205,Manish,SALES,35,72000.0,10,4.9,10000,2018-03-12,High,False,Manish,4,2018
206,Manish,SALES,35,72000.0,10,4.9,10000,2018-03-12,High,False,Manish,4,2018
207,Kiran,SALES,29,50000.0,4,3.2,0,2020-11-25,Low,False,Kiran,4,2020
208,Neha,HR,26,45000.0,2,2.8,2500,2022-06-30,Low,False,Neha,1,2022
209,Aarav,FINANCE,40,95000.0,15,5.0,10000,2015-08-19,High,False,Aarav,0,2015
210,Riya,IT,23,57388.888889,1,5.0,1000,2023-01-05,Low,False,Riya,2,2023
211,Vikas,MARKETING,30,58000.0,6,4.066667,8362,2019-04-10,Low,False,Vikas,3,2019
212,Simran,HR,29,52000.0,5,4.0,4000,2020-02-14,Low,False,Simran,1,2020
213,Sameer,FINANCE,38,<NA>,12,4.7,8000,2012-12-01,Low,False,Sameer,0,2012
214,Divya,IT,24,51000.0,5,3.9,8362,2022-10-10,Low,False,Divya,2,2022
215,<NA>,SALES,31,61000.0,7,4.0,6000,2019-06-18,Low,False,<NA>,4,2019
216,Ajay,MARKETING,29,56000.0,5,3.6,4500,2020-08-09,Low,False,Ajay,3,2020
217,Tina,HR,27,47000.0,3,2.1,2000,2021-01-20,Low,False,Tina,1,2021
218,Kabir,FINANCE,45,105000.0,20,4.8,10000,2010-05-05,High,False,Kabir,0,2010
219,Rohit,SALES,33,65000.0,8,3.0,8362,2016-07-07,Low,False,Rohit,4,2016
220,Nisha,IT,26,49000.0,3,4.3,3800,2022-04-02,Low,False,Nisha,2,2022

In [ ]:
df["Join_Month"] = df["Join_Date"].dt.month
df

,Name,Department,Age,Salary,Experience,Rating,Bonus,Join_Date,Salary_Level,Is_IT,First_Name,Dept_Code,Join_Year,Join_Month
Emp_ID,,,,,,,,,,,,,,
201,Ankit,IT,25,55000.0,5,4.2,5000,2022-01-10,Low,False,Ankit,2,2022,1
202,Pooja,HR,28,48000.0,4,3.8,3000,2021-05-20,Low,False,Pooja,1,2021,5
203,Ravi,FINANCE,29,60000.0,3,4.0,8362,2020-07-15,Low,False,Ravi,0,2020,7
204,Sonal,IT,27,57388.888889,5,4.066667,7000,2021-09-01,Low,False,Sonal,2,2021,9
205,Manish,SALES,35,72000.0,10,4.9,10000,2018-03-12,High,False,Manish,4,2018,3
206,Manish,SALES,35,72000.0,10,4.9,10000,2018-03-12,High,False,Manish,4,2018,3
207,Kiran,SALES,29,50000.0,4,3.2,0,2020-11-25,Low,False,Kiran,4,2020,11
208,Neha,HR,26,45000.0,2,2.8,2500,2022-06-30,Low,False,Neha,1,2022,6
209,Aarav,FINANCE,40,95000.0,15,5.0,10000,2015-08-19,High,False,Aarav,0,2015,8
210,Riya,IT,23,57388.888889,1,5.0,1000,2023-01-05,Low,False,Riya,2,2023,1
211,Vikas,MARKETING,30,58000.0,6,4.066667,8362,2019-04-10,Low,False,Vikas,3,2019,4
212,Simran,HR,29,52000.0,5,4.0,4000,2020-02-14,Low,False,Simran,1,2020,2
213,Sameer,FINANCE,38,<NA>,12,4.7,8000,2012-12-01,Low,False,Sameer,0,2012,12
214,Divya,IT,24,51000.0,5,3.9,8362,2022-10-10,Low,False,Divya,2,2022,10
215,<NA>,SALES,31,61000.0,7,4.0,6000,2019-06-18,Low,False,<NA>,4,2019,6
216,Ajay,MARKETING,29,56000.0,5,3.6,4500,2020-08-09,Low,False,Ajay,3,2020,8
217,Tina,HR,27,47000.0,3,2.1,2000,2021-01-20,Low,False,Tina,1,2021,1
218,Kabir,FINANCE,45,105000.0,20,4.8,10000,2010-05-05,High,False,Kabir,0,2010,5
219,Rohit,SALES,33,65000.0,8,3.0,8362,2016-07-07,Low,False,Rohit,4,2016,7
220,Nisha,IT,26,49000.0,3,4.3,3800,2022-04-02,Low,False,Nisha,2,2022,4

In [ ]:
df["Join_Date_Str"] = df["Join_Date"].dt.strftime("%d-%m-%Y")
df

,Name,Department,Age,Salary,Experience,Rating,Bonus,Join_Date,Salary_Level,Is_IT,First_Name,Dept_Code,Join_Year,Join_Month,Join_Date_Str
Emp_ID,,,,,,,,,,,,,,,
201,Ankit,IT,25,55000.0,5,4.2,5000,2022-01-10,Low,False,Ankit,2,2022,1,10-01-2022
202,Pooja,HR,28,48000.0,4,3.8,3000,2021-05-20,Low,False,Pooja,1,2021,5,20-05-2021
203,Ravi,FINANCE,29,60000.0,3,4.0,8362,2020-07-15,Low,False,Ravi,0,2020,7,15-07-2020
204,Sonal,IT,27,57388.888889,5,4.066667,7000,2021-09-01,Low,False,Sonal,2,2021,9,01-09-2021
205,Manish,SALES,35,72000.0,10,4.9,10000,2018-03-12,High,False,Manish,4,2018,3,12-03-2018
206,Manish,SALES,35,72000.0,10,4.9,10000,2018-03-12,High,False,Manish,4,2018,3,12-03-2018
207,Kiran,SALES,29,50000.0,4,3.2,0,2020-11-25,Low,False,Kiran,4,2020,11,25-11-2020
208,Neha,HR,26,45000.0,2,2.8,2500,2022-06-30,Low,False,Neha,1,2022,6,30-06-2022
209,Aarav,FINANCE,40,95000.0,15,5.0,10000,2015-08-19,High,False,Aarav,0,2015,8,19-08-2015
210,Riya,IT,23,57388.888889,1,5.0,1000,2023-01-05,Low,False,Riya,2,2023,1,05-01-2023
211,Vikas,MARKETING,30,58000.0,6,4.066667,8362,2019-04-10,Low,False,Vikas,3,2019,4,10-04-2019
212,Simran,HR,29,52000.0,5,4.0,4000,2020-02-14,Low,False,Simran,1,2020,2,14-02-2020
213,Sameer,FINANCE,38,<NA>,12,4.7,8000,2012-12-01,Low,False,Sameer,0,2012,12,01-12-2012
214,Divya,IT,24,51000.0,5,3.9,8362,2022-10-10,Low,False,Divya,2,2022,10,10-10-2022
215,<NA>,SALES,31,61000.0,7,4.0,6000,2019-06-18,Low,False,<NA>,4,2019,6,18-06-2019
216,Ajay,MARKETING,29,56000.0,5,3.6,4500,2020-08-09,Low,False,Ajay,3,2020,8,09-08-2020
217,Tina,HR,27,47000.0,3,2.1,2000,2021-01-20,Low,False,Tina,1,2021,1,20-01-2021
218,Kabir,FINANCE,45,105000.0,20,4.8,10000,2010-05-05,High,False,Kabir,0,2010,5,05-05-2010
219,Rohit,SALES,33,65000.0,8,3.0,8362,2016-07-07,Low,False,Rohit,4,2016,7,07-07-2016
220,Nisha,IT,26,49000.0,3,4.3,3800,2022-04-02,Low,False,Nisha,2,2022,4,02-04-2022

In [ ]:
df["Join_Date_IST"] = df["Join_Date"].dt.tz_localize("Asia/Kolkata")
df

,Name,Department,Age,Salary,Experience,Rating,Bonus,Join_Date,Salary_Level,Is_IT,First_Name,Dept_Code,Join_Year,Join_Month,Join_Date_Str,Join_Date_IST
Emp_ID,,,,,,,,,,,,,,,,
201,Ankit,IT,25,55000.0,5,4.2,5000,2022-01-10,Low,False,Ankit,2,2022,1,10-01-2022,2022-01-10 00:00:00+05:30
202,Pooja,HR,28,48000.0,4,3.8,3000,2021-05-20,Low,False,Pooja,1,2021,5,20-05-2021,2021-05-20 00:00:00+05:30
203,Ravi,FINANCE,29,60000.0,3,4.0,8362,2020-07-15,Low,False,Ravi,0,2020,7,15-07-2020,2020-07-15 00:00:00+05:30
204,Sonal,IT,27,57388.888889,5,4.066667,7000,2021-09-01,Low,False,Sonal,2,2021,9,01-09-2021,2021-09-01 00:00:00+05:30
205,Manish,SALES,35,72000.0,10,4.9,10000,2018-03-12,High,False,Manish,4,2018,3,12-03-2018,2018-03-12 00:00:00+05:30
206,Manish,SALES,35,72000.0,10,4.9,10000,2018-03-12,High,False,Manish,4,2018,3,12-03-2018,2018-03-12 00:00:00+05:30
207,Kiran,SALES,29,50000.0,4,3.2,0,2020-11-25,Low,False,Kiran,4,2020,11,25-11-2020,2020-11-25 00:00:00+05:30
208,Neha,HR,26,45000.0,2,2.8,2500,2022-06-30,Low,False,Neha,1,2022,6,30-06-2022,2022-06-30 00:00:00+05:30
209,Aarav,FINANCE,40,95000.0,15,5.0,10000,2015-08-19,High,False,Aarav,0,2015,8,19-08-2015,2015-08-19 00:00:00+05:30
210,Riya,IT,23,57388.888889,1,5.0,1000,2023-01-05,Low,False,Riya,2,2023,1,05-01-2023,2023-01-05 00:00:00+05:30
211,Vikas,MARKETING,30,58000.0,6,4.066667,8362,2019-04-10,Low,False,Vikas,3,2019,4,10-04-2019,2019-04-10 00:00:00+05:30
212,Simran,HR,29,52000.0,5,4.0,4000,2020-02-14,Low,False,Simran,1,2020,2,14-02-2020,2020-02-14 00:00:00+05:30
213,Sameer,FINANCE,38,<NA>,12,4.7,8000,2012-12-01,Low,False,Sameer,0,2012,12,01-12-2012,2012-12-01 00:00:00+05:30
214,Divya,IT,24,51000.0,5,3.9,8362,2022-10-10,Low,False,Divya,2,2022,10,10-10-2022,2022-10-10 00:00:00+05:30
215,<NA>,SALES,31,61000.0,7,4.0,6000,2019-06-18,Low,False,<NA>,4,2019,6,18-06-2019,2019-06-18 00:00:00+05:30
216,Ajay,MARKETING,29,56000.0,5,3.6,4500,2020-08-09,Low,False,Ajay,3,2020,8,09-08-2020,2020-08-09 00:00:00+05:30
217,Tina,HR,27,47000.0,3,2.1,2000,2021-01-20,Low,False,Tina,1,2021,1,20-01-2021,2021-01-20 00:00:00+05:30
218,Kabir,FINANCE,45,105000.0,20,4.8,10000,2010-05-05,High,False,Kabir,0,2010,5,05-05-2010,2010-05-05 00:00:00+05:30
219,Rohit,SALES,33,65000.0,8,3.0,8362,2016-07-07,Low,False,Rohit,4,2016,7,07-07-2016,2016-07-07 00:00:00+05:30
220,Nisha,IT,26,49000.0,3,4.3,3800,2022-04-02,Low,False,Nisha,2,2022,4,02-04-2022,2022-04-02 00:00:00+05:30

In [ ]:
df["Join_Date_UTC"] = df["Join_Date_IST"].dt.tz_convert("UTC")
df

,Name,Department,Age,Salary,Experience,Rating,Bonus,Join_Date,Salary_Level,Is_IT,First_Name,Dept_Code,Join_Year,Join_Month,Join_Date_Str,Join_Date_IST,Join_Date_UTC
Emp_ID,,,,,,,,,,,,,,,,,
201,Ankit,IT,25,55000.0,5,4.2,5000,2022-01-10,Low,False,Ankit,2,2022,1,10-01-2022,2022-01-10 00:00:00+05:30,2022-01-09 18:30:00+00:00
202,Pooja,HR,28,48000.0,4,3.8,3000,2021-05-20,Low,False,Pooja,1,2021,5,20-05-2021,2021-05-20 00:00:00+05:30,2021-05-19 18:30:00+00:00
203,Ravi,FINANCE,29,60000.0,3,4.0,8362,2020-07-15,Low,False,Ravi,0,2020,7,15-07-2020,2020-07-15 00:00:00+05:30,2020-07-14 18:30:00+00:00
204,Sonal,IT,27,57388.888889,5,4.066667,7000,2021-09-01,Low,False,Sonal,2,2021,9,01-09-2021,2021-09-01 00:00:00+05:30,2021-08-31 18:30:00+00:00
205,Manish,SALES,35,72000.0,10,4.9,10000,2018-03-12,High,False,Manish,4,2018,3,12-03-2018,2018-03-12 00:00:00+05:30,2018-03-11 18:30:00+00:00
206,Manish,SALES,35,72000.0,10,4.9,10000,2018-03-12,High,False,Manish,4,2018,3,12-03-2018,2018-03-12 00:00:00+05:30,2018-03-11 18:30:00+00:00
207,Kiran,SALES,29,50000.0,4,3.2,0,2020-11-25,Low,False,Kiran,4,2020,11,25-11-2020,2020-11-25 00:00:00+05:30,2020-11-24 18:30:00+00:00
208,Neha,HR,26,45000.0,2,2.8,2500,2022-06-30,Low,False,Neha,1,2022,6,30-06-2022,2022-06-30 00:00:00+05:30,2022-06-29 18:30:00+00:00
209,Aarav,FINANCE,40,95000.0,15,5.0,10000,2015-08-19,High,False,Aarav,0,2015,8,19-08-2015,2015-08-19 00:00:00+05:30,2015-08-18 18:30:00+00:00
210,Riya,IT,23,57388.888889,1,5.0,1000,2023-01-05,Low,False,Riya,2,2023,1,05-01-2023,2023-01-05 00:00:00+05:30,2023-01-04 18:30:00+00:00
211,Vikas,MARKETING,30,58000.0,6,4.066667,8362,2019-04-10,Low,False,Vikas,3,2019,4,10-04-2019,2019-04-10 00:00:00+05:30,2019-04-09 18:30:00+00:00
212,Simran,HR,29,52000.0,5,4.0,4000,2020-02-14,Low,False,Simran,1,2020,2,14-02-2020,2020-02-14 00:00:00+05:30,2020-02-13 18:30:00+00:00
213,Sameer,FINANCE,38,<NA>,12,4.7,8000,2012-12-01,Low,False,Sameer,0,2012,12,01-12-2012,2012-12-01 00:00:00+05:30,2012-11-30 18:30:00+00:00
214,Divya,IT,24,51000.0,5,3.9,8362,2022-10-10,Low,False,Divya,2,2022,10,10-10-2022,2022-10-10 00:00:00+05:30,2022-10-09 18:30:00+00:00
215,<NA>,SALES,31,61000.0,7,4.0,6000,2019-06-18,Low,False,<NA>,4,2019,6,18-06-2019,2019-06-18 00:00:00+05:30,2019-06-17 18:30:00+00:00
216,Ajay,MARKETING,29,56000.0,5,3.6,4500,2020-08-09,Low,False,Ajay,3,2020,8,09-08-2020,2020-08-09 00:00:00+05:30,2020-08-08 18:30:00+00:00
217,Tina,HR,27,47000.0,3,2.1,2000,2021-01-20,Low,False,Tina,1,2021,1,20-01-2021,2021-01-20 00:00:00+05:30,2021-01-19 18:30:00+00:00
218,Kabir,FINANCE,45,105000.0,20,4.8,10000,2010-05-05,High,False,Kabir,0,2010,5,05-05-2010,2010-05-05 00:00:00+05:30,2010-05-04 18:30:00+00:00
219,Rohit,SALES,33,65000.0,8,3.0,8362,2016-07-07,Low,False,Rohit,4,2016,7,07-07-2016,2016-07-07 00:00:00+05:30,2016-07-06 18:30:00+00:00
220,Nisha,IT,26,49000.0,3,4.3,3800,2022-04-02,Low,False,Nisha,2,2022,4,02-04-2022,2022-04-02 00:00:00+05:30,2022-04-01 18:30:00+00:00

14. Standardization / Normalization Support

In [ ]:
df["Salary"].mean()

np.float64(60830.40935672515)

In [ ]:
df["Salary"].std()

np.float64(15835.146892933628)

In [ ]:
df["Salary"].min()
df["Salary"].max()

np.float64(105000.0)

In [ ]:
df["Salary"].apply(np.mean)

Emp_ID
201     55000.000000
202     48000.000000
203     60000.000000
204     57388.888889
205     72000.000000
206     72000.000000
207     50000.000000
208     45000.000000
209     95000.000000
210     57388.888889
211     58000.000000
212     52000.000000
213              NaN
214     51000.000000
215     61000.000000
216     56000.000000
217     47000.000000
218    105000.000000
219     65000.000000
220     49000.000000
Name: Salary, dtype: float64

15. Combining & Reshaping Data

In [ ]:
dept_info = pd.DataFrame({
    "Department": ["IT", "HR", "Finance", "Sales", "Marketing"],
    "Location": ["Bangalore", "Delhi", "Mumbai", "Chennai", "Pune"]
})

In [ ]:
df_merge = pd.merge(df, dept_info, on="Department", how="inner")
df

,Name,Department,Age,Salary,Experience,Rating,Bonus,Join_Date,Salary_Level,Is_IT,First_Name,Dept_Code,Join_Year,Join_Month,Join_Date_Str,Join_Date_IST,Join_Date_UTC
Emp_ID,,,,,,,,,,,,,,,,,
201,Ankit,IT,25,55000.0,5,4.2,5000,2022-01-10,Low,False,Ankit,2,2022,1,10-01-2022,2022-01-10 00:00:00+05:30,2022-01-09 18:30:00+00:00
202,Pooja,HR,28,48000.0,4,3.8,3000,2021-05-20,Low,False,Pooja,1,2021,5,20-05-2021,2021-05-20 00:00:00+05:30,2021-05-19 18:30:00+00:00
203,Ravi,FINANCE,29,60000.0,3,4.0,8362,2020-07-15,Low,False,Ravi,0,2020,7,15-07-2020,2020-07-15 00:00:00+05:30,2020-07-14 18:30:00+00:00
204,Sonal,IT,27,57388.888889,5,4.066667,7000,2021-09-01,Low,False,Sonal,2,2021,9,01-09-2021,2021-09-01 00:00:00+05:30,2021-08-31 18:30:00+00:00
205,Manish,SALES,35,72000.0,10,4.9,10000,2018-03-12,High,False,Manish,4,2018,3,12-03-2018,2018-03-12 00:00:00+05:30,2018-03-11 18:30:00+00:00
206,Manish,SALES,35,72000.0,10,4.9,10000,2018-03-12,High,False,Manish,4,2018,3,12-03-2018,2018-03-12 00:00:00+05:30,2018-03-11 18:30:00+00:00
207,Kiran,SALES,29,50000.0,4,3.2,0,2020-11-25,Low,False,Kiran,4,2020,11,25-11-2020,2020-11-25 00:00:00+05:30,2020-11-24 18:30:00+00:00
208,Neha,HR,26,45000.0,2,2.8,2500,2022-06-30,Low,False,Neha,1,2022,6,30-06-2022,2022-06-30 00:00:00+05:30,2022-06-29 18:30:00+00:00
209,Aarav,FINANCE,40,95000.0,15,5.0,10000,2015-08-19,High,False,Aarav,0,2015,8,19-08-2015,2015-08-19 00:00:00+05:30,2015-08-18 18:30:00+00:00
210,Riya,IT,23,57388.888889,1,5.0,1000,2023-01-05,Low,False,Riya,2,2023,1,05-01-2023,2023-01-05 00:00:00+05:30,2023-01-04 18:30:00+00:00
211,Vikas,MARKETING,30,58000.0,6,4.066667,8362,2019-04-10,Low,False,Vikas,3,2019,4,10-04-2019,2019-04-10 00:00:00+05:30,2019-04-09 18:30:00+00:00
212,Simran,HR,29,52000.0,5,4.0,4000,2020-02-14,Low,False,Simran,1,2020,2,14-02-2020,2020-02-14 00:00:00+05:30,2020-02-13 18:30:00+00:00
213,Sameer,FINANCE,38,<NA>,12,4.7,8000,2012-12-01,Low,False,Sameer,0,2012,12,01-12-2012,2012-12-01 00:00:00+05:30,2012-11-30 18:30:00+00:00
214,Divya,IT,24,51000.0,5,3.9,8362,2022-10-10,Low,False,Divya,2,2022,10,10-10-2022,2022-10-10 00:00:00+05:30,2022-10-09 18:30:00+00:00
215,<NA>,SALES,31,61000.0,7,4.0,6000,2019-06-18,Low,False,<NA>,4,2019,6,18-06-2019,2019-06-18 00:00:00+05:30,2019-06-17 18:30:00+00:00
216,Ajay,MARKETING,29,56000.0,5,3.6,4500,2020-08-09,Low,False,Ajay,3,2020,8,09-08-2020,2020-08-09 00:00:00+05:30,2020-08-08 18:30:00+00:00
217,Tina,HR,27,47000.0,3,2.1,2000,2021-01-20,Low,False,Tina,1,2021,1,20-01-2021,2021-01-20 00:00:00+05:30,2021-01-19 18:30:00+00:00
218,Kabir,FINANCE,45,105000.0,20,4.8,10000,2010-05-05,High,False,Kabir,0,2010,5,05-05-2010,2010-05-05 00:00:00+05:30,2010-05-04 18:30:00+00:00
219,Rohit,SALES,33,65000.0,8,3.0,8362,2016-07-07,Low,False,Rohit,4,2016,7,07-07-2016,2016-07-07 00:00:00+05:30,2016-07-06 18:30:00+00:00
220,Nisha,IT,26,49000.0,3,4.3,3800,2022-04-02,Low,False,Nisha,2,2022,4,02-04-2022,2022-04-02 00:00:00+05:30,2022-04-01 18:30:00+00:00

In [ ]:
df_top = df.head(5)
df_bottom = df.tail(5)

df_concat = pd.concat([df_top, df_bottom])
df_concat

,Name,Department,Age,Salary,Experience,Rating,Bonus,Join_Date,Salary_Level,Is_IT,First_Name,Dept_Code,Join_Year,Join_Month,Join_Date_Str,Join_Date_IST,Join_Date_UTC
Emp_ID,,,,,,,,,,,,,,,,,
201,Ankit,IT,25,55000.0,5,4.2,5000,2022-01-10,Low,False,Ankit,2,2022,1,10-01-2022,2022-01-10 00:00:00+05:30,2022-01-09 18:30:00+00:00
202,Pooja,HR,28,48000.0,4,3.8,3000,2021-05-20,Low,False,Pooja,1,2021,5,20-05-2021,2021-05-20 00:00:00+05:30,2021-05-19 18:30:00+00:00
203,Ravi,FINANCE,29,60000.0,3,4.0,8362,2020-07-15,Low,False,Ravi,0,2020,7,15-07-2020,2020-07-15 00:00:00+05:30,2020-07-14 18:30:00+00:00
204,Sonal,IT,27,57388.888889,5,4.066667,7000,2021-09-01,Low,False,Sonal,2,2021,9,01-09-2021,2021-09-01 00:00:00+05:30,2021-08-31 18:30:00+00:00
205,Manish,SALES,35,72000.0,10,4.9,10000,2018-03-12,High,False,Manish,4,2018,3,12-03-2018,2018-03-12 00:00:00+05:30,2018-03-11 18:30:00+00:00
216,Ajay,MARKETING,29,56000.0,5,3.6,4500,2020-08-09,Low,False,Ajay,3,2020,8,09-08-2020,2020-08-09 00:00:00+05:30,2020-08-08 18:30:00+00:00
217,Tina,HR,27,47000.0,3,2.1,2000,2021-01-20,Low,False,Tina,1,2021,1,20-01-2021,2021-01-20 00:00:00+05:30,2021-01-19 18:30:00+00:00
218,Kabir,FINANCE,45,105000.0,20,4.8,10000,2010-05-05,High,False,Kabir,0,2010,5,05-05-2010,2010-05-05 00:00:00+05:30,2010-05-04 18:30:00+00:00
219,Rohit,SALES,33,65000.0,8,3.0,8362,2016-07-07,Low,False,Rohit,4,2016,7,07-07-2016,2016-07-07 00:00:00+05:30,2016-07-06 18:30:00+00:00
220,Nisha,IT,26,49000.0,3,4.3,3800,2022-04-02,Low,False,Nisha,2,2022,4,02-04-2022,2022-04-02 00:00:00+05:30,2022-04-01 18:30:00+00:00

In [ ]:
df.pivot_table(
    values="Salary",
    index="Department",
    aggfunc="mean"
)

/tmp/ipython-input-1117374423.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table(

                  Salary
Department
FINANCE     86666.666667
HR               48000.0
IT          53955.555556
MARKETING        57000.0
SALES            64000.0

16. Reading Dirty Data

In [ ]:
df = pd.read_csv("output.csv")
df

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,2014-05-02 00:00:00,3.130000e+05,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA
1,2014-05-02 00:00:00,2.384000e+06,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,USA
2,2014-05-02 00:00:00,3.420000e+05,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA
3,2014-05-02 00:00:00,4.200000e+05,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,USA
4,2014-05-02 00:00:00,5.500000e+05,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,USA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4595,2014-07-09 00:00:00,3.081667e+05,3.0,1.75,1510,6360,1.0,0,0,4,1510,0,1954,1979,501 N 143rd St,Seattle,WA 98133,USA
4596,2014-07-09 00:00:00,5.343333e+05,3.0,2.50,1460,7573,2.0,0,0,3,1460,0,1983,2009,14855 SE 10th Pl,Bellevue,WA 98007,USA
4597,2014-07-09 00:00:00,4.169042e+05,3.0,2.50,3010,7014,2.0,0,0,3,3010,0,2009,0,759 Ilwaco Pl NE,Renton,WA 98059,USA
4598,2014-07-10 00:00:00,2.034000e+05,4.0,2.00,2090,6630,1.0,0,0,3,1070,1020,1974,0,5148 S Creston St,Seattle,WA 98178,USA
4599,2014-07-10 00:00:00,2.206000e+05,3.0,2.50,1490,8102,2.0,0,0,4,1490,0,1990,0,18717 SE 258th St,Covington,WA 98042,USA

In [ ]:
df = pd.read_excel("fwc22_qatar.xlsx")
df

,GROUP_NAME,TEAM_RANK_WITHIN_GROUP,TEAM_NAME_ABBR,TEAM_NAME,GP,W,D,L,GS,GC,GD,Pts
0,Group A,1,NED,Netherlands,3,2,1,0,5,1,4,7
1,Group A,2,SEN,Senegal,3,2,0,1,5,4,1,6
2,Group A,3,ECU,Ecuador,3,1,1,1,4,3,1,4
3,Group A,4,QAT,Qatar,3,0,0,3,1,7,-6,0
4,Group B,1,ENG,England,3,2,1,0,9,2,7,7
5,Group B,2,USA,United States,3,1,2,0,2,1,1,5
6,Group B,3,IRN,Iran,3,1,0,2,4,7,-3,3
7,Group B,4,WAL,Wales,3,0,1,2,1,6,-5,1
8,Group C,1,ARG,Argentina,3,2,0,1,5,2,3,6
9,Group C,2,POL,Poland,3,1,1,1,2,2,0,4
10,Group C,3,MEX,Mexico,3,1,1,1,2,3,-1,4
11,Group C,4,KSA,Saudi Arabia,3,1,0,2,3,5,-2,3
12,Group D,1,FRA,France,3,2,0,1,6,3,3,6
13,Group D,2,AUS,Australia,3,2,0,1,3,4,-1,6
14,Group D,3,TUN,Tunisia,3,1,1,1,1,1,0,4
15,Group D,4,DEN,Denmark,3,0,1,2,1,3,-2,1
16,Group E,1,JPN,Japan,3,2,0,1,4,3,1,6
17,Group E,2,ESP,Spain,3,1,1,1,9,3,6,4
18,Group E,3,GER,Germany,3,1,1,1,6,5,1,4
19,Group E,4,CRC,Costa Rica,3,1,0,2,3,11,-8,3
20,Group F,1,MAR,Morocco,3,2,1,0,4,1,3,7
21,Group F,2,CRO,Croatia,3,1,2,0,4,1,3,5
22,Group F,3,BEL,Belgium,3,1,1,1,1,2,-1,4
23,Group F,4,CAN,Canada,3,0,0,3,2,7,-5,0
24,Group G,1,BRA,Brazil,3,2,0,1,3,1,2,6
25,Group G,2,SUI,Switzerland,3,2,0,1,4,3,1,6
26,Group G,3,CMR,Cameroon,3,1,1,1,4,4,0,4
27,Group G,4,SRB,Serbia,3,0,1,2,5,8,-3,1
28,Group H,1,POR,Portugal,3,2,0,1,6,4,2,6
29,Group H,2,KOR,South Korea,3,1,1,1,4,4,0,4
30,Group H,3,URU,Uruguay,3,1,1,1,2,2,0,4
31,Group H,4,GHA,Ghana,3,1,0,2,5,7,-2,3

In [ ]:
df = pd.read_json("fifa22.json")
df

,GROUP_A,GROUP_B,GROUP_C,GROUP_D,GROUP_E,GROUP_F,GROUP_G,GROUP_H
0,"{'RANK_1': {'TEAM': {'TEAM_NAME_ABBR': 'NED', ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,"{'RANK_1': {'TEAM': {'TEAM_NAME_ABBR': 'ENG', ...",NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,"{'RANK_1': {'TEAM': {'TEAM_NAME_ABBR': 'ARG', ...",NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,"{'RANK_1': {'TEAM': {'TEAM_NAME_ABBR': 'FRA', ...",NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,"{'RANK_1': {'TEAM': {'TEAM_NAME_ABBR': 'JPN', ...",NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,"{'RANK_1': {'TEAM': {'TEAM_NAME_ABBR': 'MAR', ...",NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,"{'RANK_1': {'TEAM': {'TEAM_NAME_ABBR': 'BRA', ...",NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{'RANK_1': {'TEAM': {'TEAM_NAME_ABBR': 'POR', ..."

# CHECKPOINT 3: DATA INTEGRATION

Vertical Data Integration (Row-wise)
Combines datasets with same structure by stacking rows.

In [ ]:
import pandas as pd

jan = pd.DataFrame({
    'EmpID': [1, 2],
    'Sales': [20000, 25000]
})

feb = pd.DataFrame({
    'EmpID': [3, 4],
    'Sales': [22000, 27000]
})

sales = pd.concat([jan, feb], ignore_index=True)

print(sales)

   EmpID  Sales
0      1  20000
1      2  25000
2      3  22000
3      4  27000

In [ ]:
marks = pd.DataFrame({
    'RollNo': [101, 102, 103],
    'Marks': [85, 90, 88]
})

attendance = pd.DataFrame({
    'RollNo': [101, 102, 103],
    'Attendance': [92, 95, 90]
})

student_data = pd.concat([marks, attendance['Attendance']], axis=1)

print(student_data)

   RollNo  Marks  Attendance
0     101     85          92
1     102     90          95
2     103     88          90

In [ ]:
students = pd.DataFrame({
    'StudentID': [1, 2, 3],
    'Name': ['Amit', 'Neha', 'Rahul']
})

results = pd.DataFrame({
    'StudentID': [1, 2],
    'CGPA': [8.5, 9.1]
})

data_inner = pd.merge(students, results, on='StudentID', how='inner')

print(data_inner)

   StudentID  Name  CGPA
0          1  Amit   8.5
1          2  Neha   9.1

Types of Joins in Data Integration

In [ ]:
pd.merge(students, results, on='StudentID', how='inner')
pd.merge(students, results, on='StudentID', how='left')
pd.merge(students, results, on='StudentID', how='right')
pd.merge(students, results, on='StudentID', how='outer')

   StudentID   Name  CGPA
0          1   Amit   8.5
1          2   Neha   9.1
2          3  Rahul   NaN

Integration Using Index Using join() Joins datasets using index instead of columns.

In [ ]:
df1 = students.set_index('StudentID')
df2 = results.set_index('StudentID')

integrated_data = df1.join(df2)

print(integrated_data)

            Name  CGPA
StudentID
1           Amit   8.5
2           Neha   9.1
3          Rahul   NaN

# CHECKPOINT 4: DATA TRANSFORMATION

1. MinMaxScaler vs StandardScaler

Both are feature scaling techniques, but they work differently.

A. MinMaxScaler

In [ ]:
from sklearn.preprocessing import MinMaxScaler
import pandas as pd

df = pd.DataFrame({'Age':[18,22,25,30,35]})
scaler = MinMaxScaler()
df_scaled = scaler.fit_transform(df)
print(df_scaled)

[[0.        ]
 [0.23529412]
 [0.41176471]
 [0.70588235]
 [1.        ]]

A. Scaling / Normalization / Standardization

Purpose: Make numerical features comparable.

In [ ]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler
import pandas as pd

df = pd.DataFrame({'Age':[18,22,25,30], 'Salary':[25000,50000,60000,80000]})

scaler = MinMaxScaler()
df[['Age','Salary']] = scaler.fit_transform(df[['Age','Salary']])
print("Min-Max Scaled:\n", df)

scaler = StandardScaler()
df_scaled = scaler.fit_transform(df[['Age','Salary']])
print("Standardized:\n", df_scaled)

Min-Max Scaled:
         Age    Salary
0  0.000000  0.000000
1  0.333333  0.454545
2  0.583333  0.636364
3  1.000000  1.000000
Standardized:
 [[-1.31267933 -1.45174713]
 [-0.3995111  -0.18935832]
 [ 0.28536507  0.3155972 ]
 [ 1.42682536  1.32550825]]